### ISSUE TITLE
Installation apache2 errors

### ISSUE THREAD

**Issue by Spiritus44** [Codiad/Codiad#1008]
Hi,

This morning I try to install Codiad, but i get some problems. To help me, I follow theses tutorials : https://github.com/Codiad/Codiad/wiki/Quick-install-on-Ubuntu and https://github.com/Codiad/Codiad/wiki/Install-on-Apache-2. I use ElementaryOS, apache2 and php7.

I take apache2 errors, systemctl status apache2.service:

juil. 02 09:54:58 PC apache2[13795]: AH00526: Syntax error on line 4 of /etc/apache2/sites-enabled/000-default.conf:
juil. 02 09:54:58 PC apache2[13795]: Either all Options must start with + or -, or no Option may.
juil. 02 09:54:58 PC apache2[13795]: Action 'configtest' failed.
juil. 02 09:54:58 PC apache2[13795]: The Apache error log may have more information.

The configuration of /etc/apache2/sites-available/default :
```
<VirtualHost *:80>
        DocumentRoot /var/www
        <Directory />
                Options -Indexes FollowSymLinks MultiViews
        </Directory>
        
        # If you want to disable php execution in your workspace, remove the comments
        #<DirectoryMatch "^.+/workspace">
        #        AllowOverride None
        #        Options -Execcgi -Indexes -FollowSymLinks -MultiViews
        #        RemoveHandler .php .phtml .php3 .php4 .php5 .cgi .htaccess
        #        Addhandler text/plain .php .phtml .php3 .php4 .php5 .cgi .htaccess
        #        php_admin_flag engine off
        #        Deny from all
        #</DirectoryMatch>
</VirtualHost> 
```

So, i guess the problem of the configuration is here : Options -Indexes FollowSymLinks MultiViews.
I don't know which options should be add (+) or remove(-).

Thanks in advance,

Spiritus44,

**Comment by 4hm3d** [comment]
try this, it should work.
```
<VirtualHost *>
        DocumentRoot /var/www/
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
                # This directive allows us to have apache2's default start page
                # in /apache2-default/, but still have / go to the right place
                RedirectMatch ^/$ /apache2-default/
        </Directory>
</VirtualHost>
```

**Comment by Spiritus44** [comment]
Ok, thanks it's work well. I've updated the wiki.
