### ISSUE TITLE
Marketplace and Live Demo not accessible

### ISSUE THREAD

**Issue by andresbono** [Codiad/Codiad#1012]
Hi all, http://market.codiad.com/ and http://demo.codiad.com/ are not accessible for me, it is returning a nginx error `502 Bad Gateway` since a few days ago. Could you take a look, please?
 Thanks!

**Comment by cheiff** [comment]
Hi, 
let me take a look. I'll set up a monitor, to be aware of this as it happens. Thank you for notifying.

**Comment by cheiff** [comment]
It is up now. I have added monitoring.

Thank you again.

**Comment by andresbono** [comment]
Great! It is up and running for me now. Thanks for the quick action!
