### ISSUE TITLE
old, insecure hashing algorithm

### ISSUE THREAD

**Issue by DanielRuf** [Codiad/Codiad#1024]
` $this->password = sha1(md5($this->password));`

Please use at least bcrypt / password_hash / password_compat.
And there are much more vulnerabilities, most are not even reported here.

You should start from the beginning and use a secure framework like Symfony or Laravel.

**Comment by daeks** [comment]
You are welcome to contribute to the project.

**Comment by DanielRuf** [comment]
See #1047
