### ISSUE TITLE
Dumped users.php, files overwritten

### ISSUE THREAD

**Issue by skylordjason** [Codiad/Codiad#1027]
Codidad seems to have failed spectacularly.

I tried saving a project file, and then it just stopped responding. Then it logged me out. I refreshed the project and I realized that every file I had open was now empty. The users.php file is also empty, so I can't even log in to codidad anymore.

Ending the panic attack I just had, does anyone have an explanation for it or a way to reset the users.php file?

**Comment by daeks** [comment]
I haven't heard anything with regards to your problem description. Maybe others have seen such a behavior. I would recommend to add some information about your system and server configuration.

**Comment by skylordjason** [comment]
Long story short, server was misconfigured and ran out of space.
