### ISSUE TITLE
CMS integration

### ISSUE THREAD

**Issue by ivangretsky** [Codiad/Codiad#1039]
Good day!

Codiad is super cool. Thanks everybody for making it.

I am thinking about developing a module for my CMS of choice, which would integrate Codiad to allow on-site editing. 

1. Do you think it is possible? Are there any examples?
2. The main part of integration seems to be user sharing. Could you please give insights how this should be done?

**Comment by jpl42** [comment]
You could create your own authentication module based on one of the examples [found in the wiki](https://github.com/Codiad/Codiad/wiki/External-Auth). Depending on the CMS you are using, you may be able to get up and running very quickly with the [SQL authentication example](https://github.com/QMXTech/Codiad-SQLExternalAuth).

**Comment by ivangretsky** [comment]
Thank you!
