### ISSUE TITLE
500 Error in components/filemanager/controller.php

### ISSUE THREAD

**Issue by ExplosiveNight** [Codiad/Codiad#1055]
Enviroment:
CentOS 7.0
CentOS Webpanel running Apache 2.4.29, PHP 7.0.27

So, I've been trying to install Codiad on my new VPS for a couple of days now, without any success. Codiad ran fine on my old shared host, and I cannot seem to find the issue. I have reinstalled Codiad about 5 times. When I log in, the project currently selected just displays the spinning dots forever and ever. I get an error in the browser console that says
 ```
jquery.min.js:4 GET https://explosivenight.us/ide/components/filemanager/controller.php?action=index&path=site 500 ()
```
This seems to be some sort of issue with jquery, but I simply cannot find what is wrong.

**Comment by ExplosiveNight** [comment]
Updating my PHP version to 7.1 seems to have fixed the problem.

**Comment by seanvree** [comment]
I can't get past this error right now either.  I"m on PHP version 7.2.1 running on Windows IIS. 

Deleted all the plug-ins, but I get the error below:

```
jquery.min.js:4 GET https://mydomain.com/codiad/components/filemanager/controller.php?action=index&path=JBOPS 500 (Internal Server Error)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
f.(anonymous function) @ jquery.min.js:4
index @ init.js:285
(anonymous) @ init.js:54
o @ jquery.min.js:2
fireWith @ jquery.min.js:2
w @ jquery.min.js:4
d @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
f.(anonymous function) @ jquery.min.js:4
loadCurrent @ init.js:48
init @ init.js:21
(anonymous) @ init.js:12
o @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
07:17:26.018 

```

**Comment by ExplosiveNight** [comment]
Currently, Codiad does not seem to work properly on any PHP version greater than 7.0.30, which is what I had to downgrade to to get Codiad to work. 7.1 and 7.2 seem to break it, causing an error in the file manager. Don't expect this to get fixed any time soon though, because Codiad hasn't been updated in over two years.

**Comment by abenkorich** [comment]
It's related to these 2 new functions in php 7.2;
http://php.net/manual/ru/function.mb-ord.php
http://php.net/manual/ru/function.mb-chr.php

This solution worked for me:
Run this from codiad root directory: 
`find ./ -exec sed -i 's/mb_chr/codiad_mb_chr/g; s/mb_ord/codiad_mb_ord/g' {} \;`

Reference: 
https://github.com/Codiad/Codiad/issues/1061

**Comment by icedvigilante** [comment]
Thank you. This helped me a lot.

**Comment by r1-dev-praxiv** [comment]
`` `` `` `` `` `` `` `` ` ` ``
