### ISSUE TITLE
Codiad Theme Feisty

### ISSUE THREAD

**Issue by tobx** [Codiad/Codiad#1062]
Hi,

I have put a lot of work in creating a new Codiad theme last week. Nothing compared to creating Codiad itself though :)

It would be great, if you could test it, report issues and hopefully include it into the marketplace.

I named the theme "Feisty" and you can find it [here at GitHub](https://github.com/tobx/Codiad-Theme-Feisty).

Cheers,
Tobi

**Comment by Sh4d0wF1gh7** [comment]
Great work... Love it
