### ISSUE TITLE
[Critical] Saving a file after editing leads to random garbage content

### ISSUE THREAD

**Issue by hexxone** [Codiad/Codiad#1072]
I was just creating a language file for a bot of mine, when I noticed after saving and restarting the bot, I'd get syntax errors from the language file. And I was pretty confused since Codiad didnt show anything wrong. So I saved again, still same problem. After some time I refreshed the page (F5) and suddenly I saw the problem. Large chunks of the file where I made changes have been replaced randomly with garbage/some parts of the older text I guess.

How it should look
![codiad_wtf1](https://user-images.githubusercontent.com/5312542/39452977-831e8be0-4cd4-11e8-9e92-755dd5b8a57b.JPG)

How it looked after the refresh
![codiad_wtf2](https://user-images.githubusercontent.com/5312542/39452978-83398882-4cd4-11e8-8ccb-433fb0186e02.JPG)

I cannot tell why this suddenly appeared, Maybe its a special character in the file or idk, but this is a really annoying issue, and if this doesnt get fixed fast Ill probably have to leave for another web IDE :(

**Comment by thexbasic** [comment]
Bump
