### ISSUE TITLE
Cannot access market place

### ISSUE THREAD

**Issue by DovaMerith** [Codiad/Codiad#1091]
![cidad](https://user-images.githubusercontent.com/10422110/47234411-a3b07c00-d38a-11e8-9188-48e41d25637a.png)

This is what happens, and ive checked the http://market.codiad.com/json/ link, got 
``<br />
<b>Fatal error</b>:  Maximum execution time of 30 seconds exceeded in <b>/srv/users/serverpilot/apps/codiadmarket/public/json/index.php</b> on line <b>35</b><br />`` as an error

**Comment by cheiff** [comment]
I have increased execution time. Can you please try again?

**Comment by DovaMerith** [comment]
okay, I got a huge wall of text 
https://pastebin.com/m4aDM6TP

now what?

**Comment by DovaMerith** [comment]
![codasd](https://user-images.githubusercontent.com/10422110/47258542-767ad100-d451-11e8-9c98-4a41efe67cc4.png)
Checked my version for you, I had followed the Ubuntu quick install instructions

**Comment by cheiff** [comment]
The marketplace is normally visited from within Codiad. There you should get a list of plugins to install.

**Comment by DovaMerith** [comment]
Okay, i just changed away from the nightly build and now its working fine,
