### ISSUE TITLE
PHP Fatal error:  Cannot redeclare mb_ord()

### ISSUE THREAD

**Issue by ashwenn** [Codiad/Codiad#1096]
I installed Codiad as the instruction goes. When I create a project and it tries to access `/components/filemanager/controller.php?action=index&path=/project/path`, the response is 500 Internal Server Error.

PHP-fpm responses:
> PHP message: PHP Fatal error:  Cannot redeclare mb_ord() in /var/www/codiad/lib/diff_match_patch.php on line 2079  

My server is Ubuntu 18.04, Nginx 1.14.0, php 7.2 fpm.

What's wrong?

Thanks in advance.

**Comment by ElkoHoll** [comment]
Read the solution here: https://github.com/Codiad/Codiad/issues/1082

**Comment by ashwenn** [comment]
Commenting out the 2 functions works.
