### ISSUE TITLE
Diaglog box doesn't fit the screen.

### ISSUE THREAD

**Issue by kcubeterm** [Codiad/Codiad#1116]
![Screenshot_2020-01-08-16-55-20-060_com android chrome](https://user-images.githubusercontent.com/50498359/71974788-5c850400-3238-11ea-872c-656c3d2cf420.jpg)

![Screenshot_2020-01-08-16-54-55-899_com android chrome](https://user-images.githubusercontent.com/50498359/71974808-6ad32000-3238-11ea-9e96-022cf2493b13.jpg)

You can see above two images, i am using codiad ide in android chrome, when I open settings tab ,the dialog box doesn't fit screen, i tried it in desktop site mode also ,

the server is running in termux(android terminal)

**Comment by X25guru** [comment]
Drag the window with the marker onto the screen. If you have persistent modal set it will display the window in the last place you dragged it. If you chance screen sizes it may be off the screen.

**Comment by kcubeterm** [comment]
Thanks, but i can't drag the diaglog with the marker.

**Comment by kcubeterm** [comment]
I got the solution,not a solution but a little hacks, the hack is simple, when i need to use dialog box(settings,create etc) then turn on desktop mode in chrome or whatever you use, then clear the all cache related to codiad website, from site settings in chrome.
