### ISSUE TITLE
When deleting a project, follows symlinks and deletes linked files, too.

### ISSUE THREAD

**Issue by spoulson** [Codiad/Codiad#153]
I installed Codiad with a new project.
I added a symlink to another dir outside of Codiad.
Codiad was able to see the linked files from the IDE.
Then, I decided it would make more sense to follow the tip in the Wiki to create a project, and replace the project dir with a symlink.
So, I used the IDE function to delete the original project.
It took a little while I wondered why.  Then, I found that it had deleted all non-hidden files in the linked directory!
Fortunately, all files were recoverable.
However, I think Codiad should not follow symlinks when deleting projects.

**Comment by jpl42** [comment]
Issue #964 proves something needs to be done about this.

**Comment by IamSpacename** [comment]
sorry but whoever made this delete without means of recovery or BREAKING the delete process, should not be coding.

**Comment by IamSpacename** [comment]
Who doesn't send the deleteds to the bin/trash ?  .. whoever you are, I am grinding my teeth at you tonight. 
-- and if anyone cares, I'm gutting this to work in favor of my work..not against me.
