### ISSUE TITLE
Preview Button

### ISSUE THREAD

**Issue by x-nz** [Codiad/Codiad#38]
It would be nice to have a preview button to quickly check the page you are working on. (mostly for HTML)

**Comment by mkotsovoulou** [comment]
I found a workaround to Preview Projects from your webroot public_html folder
**Add/Change the following to config.php**

define("WWW_PATH", "fullpath to your public_html"); // for example /home/users/xxx/public_html
define("HOST", $_SERVER["HTTP_HOST"]);

define("WORKSPACE", WWW_PATH . "/");
define("WSURL", HOST );

Then create a new project (without using the absolute path). The project will be created on your public_html. Preview now works...
