### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by Fluidbyte** [Codiad/Codiad#422]
I'm putting in this issue as a placeholder/tracker for a UI/UX rework. I have some ideas on cleaning up the UI a bit and adding some improvements.

One major change will be the removal of all themes (except `default`) from the core. I know there's talk of a theme marketplace or something similar and I would like to clear out the core so any expansion (just like with plugins) is truly an expansion, and not included in the default base and 'flipped on'.

I'm rolling around some ideas and will have more here as it comes about.

**Comment by daeks** [comment]
I would like to close that one as almost all points are now included
