### ISSUE TITLE
Bug Where Text Becomes Jumbled

### ISSUE THREAD

**Issue by MrGrinst** [Codiad/Codiad#450]
I'm running Codiad on a live site now doing some basic development, and my buddies and I keep running into a bug where text we type will be jumbled after switching to another tab and back again. This can be remedied by hitting "Ctrl-Z" but does anyone know what might be causing this?

**Comment by brandon95547** [comment]
I have been using Codiad for some time now and so far, I'm impressed. When I say using Codiad, I mean I have multiple projects, Codegit (a plugin) for Git integration to enforce a safe promotion process and overall text editor. 

I honestly can't say at this time what I would do to improve it, but there is one thing that comes to mind. When this is installed on some hosts I have dealt with such as bluehost and hostmonster, I have experienced a saving issue. When holding down CTRL or Command (for mac) S, you have to press it again to then get an alert that warns you, when I have to cancel and ten finally hit save again to save the file. 

I'm not sure if this is some kind of permissions issue, but it does happen.
