### ISSUE TITLE
Project refactoring

### ISSUE THREAD

**Issue by yguedidi** [Codiad/Codiad#451]
Short: I propose to replace the _absolute path project_ notion by a _in workspace project_ notion.

Long: Currently projects are saved in `data/projects.php`, but the `path` value of a project is different for an absolute project and a project in workspace, it's not too **consistent**..
That cause that we have to test if it's a path or just a project dirname in the code.

I propose to always save projects with an absolute path, even if they are in workspace. 

Advantages :
- Less code, no more need to test if it's an absolute path or not to prepend the root
- More consitent
- Increase compatibility with Windows, cause no more check for an absolute path with `'/' == $path[0]`
- Easy to implement an `isInWorkspace()` function for specific cases. (by check if the `path` value begin with the `WORKSPACE` constant)

@Fluidbyte it's just my opinion, but it's your project ;)

**Comment by daeks** [comment]
small update: abspath projects are now possible on win based systems, so we could go forward with this approach as well.
