### ISSUE TITLE
Snippets plugin

### ISSUE THREAD

**Issue by pradeepmurugesan** [Codiad/Codiad#490]
I would like to build a snippets plugin for codiad. The plugin allows

1. to create a predefined snippet tag and a corresponding snippet. 
2. in the editor when the user enters the key word and hit tab we will load the snippet .

i thought we can have a json to store the snippet as a key-value pair and they will define the snippet scope as c,js or html.

we will one file per scope, for example snippet.js will be looked into if the user edits a js file and hits tab. the json will have the following format

```
{
     if:     "if(condition) { }",
     for:   "for (init ;condition ;increment) { } ,
}
```
Including tab stops will be a part of enhancement in the upcoming versions.

Do you guys think this will be useful plugin ? Also please comment on the implementation idea as well.

**Comment by daeks** [comment]
https://github.com/Andr3as/Codiad-CompletePlus
