### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by Arethus** [Codiad/Codiad#580]
Hi, I have the collaboration plugin and after ~5 minutes of collaborating when my friend or I try to open 'index.php' again, there is an infinite loading wheel. I have tried removing all plugins/readding but it will not work. I restart nginx too. Any ideas?

I just realised it seems to be only php files having this problem as when php file is broken a css file works fine. Also, I tried in firefox, IE, and chromium, all have the problem.

**Comment by spiner2000** [comment]
problem reoccured in 2.5.4

**Comment by InfiltrationIT** [comment]
reoccurred in Version v.2.7.2

**Comment by SimonBrodtmann** [comment]
Same here with 2.8.4. I deleted the whole folder and did a fresh install. That did not help.
