### ISSUE TITLE
File contents "scrambled" after copy/paste operations

### ISSUE THREAD

**Issue by Dave-Morton** [Codiad/Codiad#618]
While working on either PHP or HTML files in Codiad (possibly other file types, too - I just haven't been working on other types), If I paste any content (plain text, code, etc.) into the file I'm working on there's a fairly high likelihood that either the content I just pasted or the content surrounding it will become "scrambled". An example is illustrated, below:

Let's say I have the following code already in place:

```
    error_log("There is a file type missing. overlayImageFilename = $overlayImageFilename, fileIndex = $fileIndex\n", 3, "my.error.log");
```

and I want to paste the following into the next line down:

```
    header('Location:myFile.php'); // redirect to re-run the script
```

What sometimes ends up happening (about 30-40% of the time) looks something like this:

```
    error_log("There is a file type missing. overlayImageFilename = $overlayImageFilename, fileIndex = $fileIndex\n", 3, "emr.yor.log");
    heeadr('Laotcnio:myFile.php'); // redirect to re-run the script
```

If I'm not paying attention, this can result in a significant amount of debugging time, trying to locate the bugs the text scrambling generates, and even if I'm looking out for this problem, it still represents a great deal of "wasted time" to go back and re-write what was scrambled.

I'm using Codiad in the most recent version of Chrome, with no extensions enabled. If further information is necessary, I'll be happy to supply what I can.

**Comment by daeks** [comment]
Codiad has updated its internal editor which should resolve this issue. Please check it and state your result at #516
