### ISSUE TITLE
Settings saving issue

### ISSUE THREAD

**Issue by rwaness** [Codiad/Codiad#624]
Hello,

I note that if i change my settings, they are not saved when I login the next time.... ?

Am I the only one, or is it a rela bug ?

Thanks for this wonderful project and good continuation

Erwan

**Comment by smolinari** [comment]
Ok, I thought coding on a tablet would be unheard of and was taught differently and now coding on a phone? Here, I'd have to say, no way!....:-D

Scott

**Comment by daeks** [comment]
This issue is not really related with coding on phones, it is more related with synchronisation of settings between devices and that is included since july 2014 ;-) (just closed old already implemented issues)

**Comment by smolinari** [comment]
Yeah, I saw that. But still.... coding on a phone?;-) I don't think so.

Scott

**Comment by rwaness** [comment]
Maybe not you, but certainly someone else... Otherwise I would not ask ;)
Erwan

2015-03-18 10:47 GMT-04:00 Scott <notifications@github.com>:

**Comment by smolinari** [comment]
Sorry, but the expectation of coding on a phone with Codiad is like asking to watch a film through powerful binoculars in a theater. Even from the back seats, you'll only see a portion of the whole screen. LOL!:-D

Scott
