### ISSUE TITLE
Codiad Plugins

### ISSUE THREAD

**Issue by daeks** [Codiad/Codiad#627]
Dear all,

I noticed several plugin repos which are currently not in our marketplace and can not be accessed directly from it.

https://github.com/pradeepmurugesan/Codiad-Snippets
https://github.com/newsocialifecom/Codiad-Autocomplete
https://github.com/bartonjd/Codiad-SVNAdmin
https://github.com/RustyGumbo/Codiad-FileUse
https://github.com/bartonjd/codiad-svn-checkout
https://github.com/dev-rke/Codiad-ToDo
https://github.com/ccvca/LaTeXBuilder

https://github.com/Andr3as/Codiad-Favorites
https://github.com/Andr3as/Codiad-CodeGit
https://github.com/Andr3as/Codiad-DragDrop
https://github.com/Andr3as/Codiad-MiniMap

@pradeepmurugesan, @newsocialifecom, @bartonjd, @RustyGumbo, @dev-rke, @ccvca, @Andr3as is there any reason why these repos as long as they fit stability requirements are not added to our marketplace?

**Comment by waptug** [comment]
Hi Codiad/Codiad,

I&#39;d like to add you to my professional network on LinkedIn.

- Michael Scott

Accept: https://www.linkedin.com/blink?simpleRedirect=30Oej4UczsSd3gUd3ANdPcTejkZh4BKrSBQonhFtCVF9C9kck9agR1mfnBBiShBsC5EsOpQsSlRpRZBt6BSrCAZqSkConhzbmlQqnpKqiRQsSlRpORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4CqPkJcmpKd6pxdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719522270539778_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6IRbj5CrzhCojpFbmJxcSNDriQZp6BB9A5LrC5kj6ZQj7BgckheqBpacRBHiQhkj5ZagDBVrSFBe51mgANQlA8Td7pysAtBdmsSrm98jztyonwPozp6omVhiQx4gRpNqlYMpDlJmCZIpSJdekdDhQVhgQITd4F7sk5ns78OqRZgsm9xgl5cp7FNuklRs7hliRxvliRGq5pJuChfrAFxdC9JdCpajRdNoDllgk51tTBSqQQRkQZLrz57kk4Zp6BLr2pQsSlRpRZBt6BSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCqPkJcmpKd6pxdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5973719522270539778_500&amp;markAsRead=This email was intended for Codiad/Codiad Codiad/Codiad. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoipQsSlRpRZBt6BSrCAZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CqPkJcmpKd6pxdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719522270539778_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by waptug** [comment]
Michael Scott McGinn would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=30Oej4UczsSd3gUd3ANdPcTejkZh4BKrSBQonhFtCVF9C9kck9agR1mfnBBiShBsC5EsOoVclZMu6lvtCVFfmJB9D9Bp6VFrmlObnhMpmdzoiRybmtSrCBvrmRLoORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4Cuj8JpCIOpD9EdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719522270539778_500&markAsRead=

View Michael Scott McGinn&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=0VclZMu6lvtCVFfmJB9D9Bp6VFrmlObnhMpmdzoiRybmtSrCBvrmRLoORIrmkZpSVFqSdxsDgCtD1KfngCuj8JpCIOpD9EdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719522270539778_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9j4TdPcNcP4JejhBdztAejwUoz8RcPsUc6oUe3cUp3xBp6dBdSgUc3pxdP0PoP0Rp2QOe3kPd3cNcORFgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACc38VcjwOdPoQd3wQej4TcPsVdjRAqmsCej5vs7xBnTpKqjRHpipytndKtiRCbmdypmRvrmRLoORIrmkZpSVFqSdxsDgCrSZDfngCuj8JpCIOpD9EdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719522270539778_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=uj8JpCIOpD9EdCAJqS4Pr6tJbjRAqmkCpQYThPoUsC5yekkVj4x8rA5mjRZEimUMpmZnskAJhAtfoPB4qQ9orQUMhQcTjklqt5tjuCNUm5ZGtDlihRpNsCpJhQ4MiAYTomZfu3pqimh5sDcUemFUm3pJiSRzk4EJekBprCIOjSJlcmtdcClnej54oANxk74Pl5kQrzARjltEozhFmmVGuA94cn9RrAwOtll1gk51pSEUsk8Us4VbcAthgjRAqmZI9zANnT1UplZSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCuj8JpCIOpD9EdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5973719522270539778_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9zANnT1UplZSrCAZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cuj8JpCIOpD9EdCAJqS4Pr6tJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719522270539778_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by daeks** [comment]
Issue is currently locked to prevent further spamming.
