### ISSUE TITLE
Saving bug

### ISSUE THREAD

**Issue by aeterna** [Codiad/Codiad#637]
I've noticed that sometimes when saving (with ctrl+s) Codiad will prompt me saying "Server has a more updated copy of the file. Would you like to refresh the contents ? Pressing no will cause your changes to override the server's copy upon next save."

If I press OK, instead of no, it will completely wipe the open file - but if I press cancel and then save again, it will save normally.

I'm using Chrome v34.0.1847.116 / Win 8 (although the codiad installation is on a linux host)

I was able to find where it was coming from, but I'm unsure why the response would be 'Client is out of sync' when nothing was changed. 

>components/filemanager/init.js

```
                if (resp.status == 'success') {
                    codiad.message.success(i18n('File saved'));
                    if (typeof callbacks.success === 'function'){
                        var context = callbacks.context || _this;
                        callbacks.success.call(context, resp.data.mtime);
                    }
                } else {
                    if (resp.message == 'Client is out of sync') {
                        var reload = confirm(
                            "Server has a more updated copy of the file. Would "+
                            "you like to refresh the contents ? Pressing no will "+
                            "cause your changes to override the server's copy upon "+
                            "next save."
                        );
                        if (reload) {
                            codiad.active.close(path);
                            codiad.active.removeDraft(path);
                            _this.openFile(path);
                        } else {
                            var session = codiad.editor.getActive().getSession();
                            session.serverMTime = null;
                            session.untainted = null;
                        }
                    } else codiad.message.error('File could not be saved');
                    if (typeof callbacks.error === 'function') {
                        var context = callbacks.context || _this;
                        callbacks.error.apply(context, [resp.data]);
                    }
                }
```

**Comment by waptug** [comment]
Hi Codiad/Codiad,

I&#39;d like to add you to my professional network on LinkedIn.

- Michael Scott

Accept: https://www.linkedin.com/blink?simpleRedirect=c3wQd30Scj4UejsQej4TcPsVdjR4imVLqnhxt6BSrCAChQZJmABNc5wZumlbp6lOomxP9DhPpnlDnSlQqnpKqjRHpipxt6cJpnhFtCVFbnhPpnlDbmNJpjRDrCBHoS5Ot2pBt6BSrABDpl9BsD0ZoipxbndRqjhCojpFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719497889050624_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1xbndRqjhCojpFbnhKoDsNtPRAqmkCkmp8qAFRpP5Sh4NkuAN9i6dxd7hKd4AMpRBooRpipnB6oSR9i7FQmBlvd4cPokAJrSRDlQxQe3lkdkJitRATlS8RjnBah4BqllxfqANJikhdu6Beqzt1dj4Uj5hFgzxhpShxumhRp7F3llARkmpHkSRUcCZhi51fl4lDj5cViAJ6hSRKulpdul18d4hvkD5ytll1gk51ijBJmANGcktSjkxhgjRAqmZI9DhPpnlDnSlQqnpKqjRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2pxbndRqjhCojpFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5973719497889050624_500&amp;markAsRead=This email was intended for Codiad/Codiad Codiad/Codiad. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9DhPpnlDnSlQqnpKqjRHpipIsBlBoSBSsCljsClJrThPtmcZoipxbndRqjhCojpFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719497889050624_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by waptug** [comment]
Michael Scott McGinn would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Me3gQc3oNcjwVdPgVcjsPdPARfkh9rCZFt65QqnpKqip7jSRqin4Mm3RVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CERbj9RoDBOq3pFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719497889050624_500&markAsRead=

View Michael Scott McGinn&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CERbj9RoDBOq3pFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719497889050624_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kNdPsPcjcNbjwMdClxdzoOpmoNdjsPcSdApCcScPoNpCkRcS4Rc3kRoj1Ad6hxcP0Jdz0Nc3AMczcJqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Ud3gMdz4Ne3ATd3ANdPcTejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CERbj9RoDBOq3pFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719497889050624_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1GdiQOtm9VsCwSqiRQrC9TcnsZp6BB9BBpl6VvdQ5hdB4OplBit4Bkk4ZMjSdIiCtRi48NenxQpCNCgktMbmFbhmFBgCxgpB5edDBWrDFWk2RBulZOrm9CqR4QrjxWsPhvhkt4iRxRel1gq5pmsz4Vl4h6d6ldjTdqbmANr4dGdB1itkVOtDlAqn5plTx3k4dogAF9tD5AoThQrR9kk2RHi35Gr4pccDllgk51gn54kD5WtB16sCl8kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CERbj9RoDBOq3pFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5973719497889050624_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CERbj9RoDBOq3pFbnhKoDsNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5973719497889050624_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by daeks** [comment]
Issue is currently locked to prevent further spamming.
