### ISSUE TITLE
Uploading files do not work

### ISSUE THREAD

**Issue by troyane** [Codiad/Codiad#652]
I can't upload files to folders using Codiad's upload interface. File uploads (progressbar moves to 100%), and it looks like file is uploaded completely, but there's no this file in folder.

I'm using Apache.
What kind of information do I need to provide to help to solve this issue?

**Comment by m-sakano** [comment]
Hi, I produced such error.  Complete! is shown, but file is not uploaded.

In my case,
upload_max_filesize = 2M (php.ini)
File size I tried to upload > 2M

Of cause, small (up to 2M) files can be uploaded.

Thanks.
