### ISSUE TITLE
Absolute Path  Problem

### ISSUE THREAD

**Issue by CtrlAltCris** [Codiad/Codiad#679]
Hey guys, i have a new problem:

I try create new project but when i write the absolute path, i output this error:

"Absolute Path Only Allowed for /var/zpanel/hostdata/zadmin/public_html/codiad,/home"

I try absolute path like /public_html/projec1 and /public_html/ and /home/zadmin/project1, and doesnt work.

Any suggestion ? 
Tnks!

**Comment by Jan4them** [comment]
Even if it's an old post but staying fully relevant, i would like to add a notice done : 
In the "Explore" pan, when using the contextual menu (right click) on a file belonging to a project documented with an absolute path like '/var/www/sda/0/e/myDomain', the list of the proposed tasks is not the same compared to file in the normal Folder projects,
 >  "download" & "preview" features are missing.
Is it a normal feature or ?

**Comment by akkaweb** [comment]
Still relevant in 2018 (end of it). Anyway, the way I fixed my issue is replacing:

`define("WHITEPATHS", BASE_PATH . ",/home");`

with

`define("WHITEPATHS", BASE_PATH . ",/var/www");`

This could also work if you already have projects setup in `/home`

`define("WHITEPATHS", BASE_PATH . ",/home,/var/www");`
