### ISSUE TITLE
Right-click in Explorer doesn't work with many files/folders

### ISSUE THREAD

**Issue by ghost** [Codiad/Codiad#685]
When the number of files/folders in the Explore window gets past the half-way point of the display - which forces the right-click menu to open above the object that was right-clicked - when you go to make a selection the right-click menu immediately closes.  I can find no way around this.

![1](https://cloud.githubusercontent.com/assets/732189/3575535/26188c6a-0b89-11e4-8607-e8094eb66cfe.png)

![2](https://cloud.githubusercontent.com/assets/732189/3575534/26179f26-0b89-11e4-9c7e-da170504641d.png)

**Comment by loopByte** [comment]
I have the same problem here
