### ISSUE TITLE
"Close All" button has no desciption when being hovered

### ISSUE THREAD

**Issue by afritsch** [Codiad/Codiad#702]
I had to click it to see what it does. And a safety question ("Do you really want to close all open files?") would be neat too, for accidental clicks.

I found another issue with this button:
When having unsaved files I get the question to save them, but when clicking cancel instead of cancelling the closing progress, those files do simply NOT get saved. Either the "cancel" button should be renamed or the behaviour should be changed.

**Comment by daeks** [comment]
I would currently reject to have always a popup as we should not show unnesscary popups during the work with Codiad
