### ISSUE TITLE
Inconsistent sever text filename in synchronizeText

### ISSUE THREAD

**Issue by Eskimo151** [Codiad/Codiad#725]
Everytime I type in an HTML document.

![codiad](https://cloud.githubusercontent.com/assets/9421822/4798033/696ad750-5e10-11e4-9fe6-607c5f076bc8.gif)

**Comment by Calinou** [comment]
I get this issue whenever the Collaborate plugin is installed. Using latest Git (https://github.com/Codiad/Codiad/commit/98d992acf18ed240edd4ea317d862d4469bbed39) of both plugins and editor.
