### ISSUE TITLE
Shows some warnings on marketplace

### ISSUE THREAD

**Issue by athulrajdr** [Codiad/Codiad#730]
marketplace dialog box shows warnings. 
How can i solve this issue?

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\codiad\components\market\class.market.php on line 75
Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in C:\xampp\htdocs\codiad\components\market\class.market.php on line 170

Warning: file_get_contents(https://raw.github.com/daeks/Codiad-DiffViewer/master/plugin.json): failed to open stream: Invalid argument in C:\xampp\htdocs\codiad\components\market\class.market.php on line 170

Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in C:\xampp\htdocs\codiad\components\market\class.market.php on line 170

**Comment by daeks** [comment]
Tested on Apache2.4 and windows 2008 without any issue. So its XAMPP specific.
