### ISSUE TITLE
ACE editor not having 100% height on load of active files

### ISSUE THREAD

**Issue by nerodark** [Codiad/Codiad#733]
All files that I open manually by the tree on the left the editor shows correctly.
But files that are open automatically on the load of a project, sometimes the editor does not show correctly. Can't tell for the moment if it's done by the editor or by codiad.
![sans titre](https://cloud.githubusercontent.com/assets/4216155/5062963/4415cf6e-6da1-11e4-8e76-7d4c8e628b84.png)

can reproduce on all popular browsers on windows

when we give focus to the editor, it goes full height.

**Comment by daeks** [comment]
I would like to close that as I really cant confirm this issue and it is really minor. If there a more complains, we can reopen it again.
