### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by evertton** [Codiad/Codiad#742]
I think we should use tools to automate the verification of coding style. Thus, we keep the code cleaner and using the same coding standard.

We may use JSHint for javascript. And also evaluate the static analysis tools available for php code. I suggest the following [PHP CodeSniffer](http://pear.php.net/package/PHP_CodeSniffer).

**Comment by evertton** [comment]
I made some changes in my master fork, but could not make the Travis CI run a building.

[![Build Status](https://travis-ci.org/evertton/Codiad.svg)](https://travis-ci.org/evertton/Codiad)

**Comment by evertton** [comment]
I had success with Travis CI and Phing... see the badge in the previous review.  :smile:
We need to define the coding standard. In my repository setted PSR-2 randomly.

> Is need still hit some details of the Travis CI configuration...

**Comment by daeks** [comment]
nice one :) is there some kind of documentation which standards are available?

**Comment by evertton** [comment]
Yes, is possible. Just change this line:
```xml
<phpcodesniffer standard="<path to ruleset>">
```

**Comment by daeks** [comment]
then i would like to start with an own standard, which covers correct EOL and correct tab width (4 spaces)

**Comment by smolinari** [comment]
I have a poll currently (and coincidentally) running in the PHP Developers group on G+ and, as it seems, most everyone is following PSR2 or chose "it depends" (which I would think means, it depends on the project). I think following PSR2 would be safe choice though (and it covers correct EOL and 4 spaces per tab, if I recall correctly).

https://plus.google.com/u/0/+scottmolinari/posts/TVheJyhGko5 

Scott

**Comment by evertton** [comment]
Travis CI failure in construction, if the coding patterns are not correct.

**As we have not reached a conclusion about which standard to use, set the `PSR2` for now.**

1. I do a pull request? Or...
2. Should I start writing our own coding standard? In this case, we need to discuss which style to adopt.

This is the build status of my fork: [![Build Status](https://travis-ci.org/evertton/Codiad.svg?branch=master)](https://travis-ci.org/evertton/Codiad)

 > It would be nice look at other points where we can apply the Phing.

**Comment by daeks** [comment]
PSR2 is ok and yes a PR would be nice. If the build fails we have to look which standard rule is violated
