### ISSUE TITLE
Save bug on CentOS 6

### ISSUE THREAD

**Issue by TheLonelyDev** [Codiad/Codiad#746]
Hello,

I installed Codiad on my CentOS 6 production machine today (Codiad ran without any bugs on Debian 6 & 7). I had ome issues regarding the saving. 

When saving a file for the first time, no error comes up. When you save it a second time it shows an error, the "could not save...". When looking in fiddler you can see that it gets a 5xx error (500 to be specific). If you try a third time then you get the alert that the server has another version of the file, when you hit 'ok' then the file will be reloaded and the content will be empty. When canceling and you try to save a fourth time then the file is finally saved.
How to reproduce this bug:
(On creating a new file; modify the content and then save then file and then those steps will reproduce the bug)
1. Modify the file content.
2. Save the file (ctrl+s), an error would pop-up.
(Wait a second)
3. Save the file (ctrl+s), an alert would pop-up about file versions that don't match (local <-> server).
4. Save the file (ctrl+s), a success message would appear.

I could reproduce this issue on 3 machines with all fresh installations. (Tried both 32 and 64Bit).
Files were owned by apache (the user that is used by apache on CentOS); (chown apache:apache -R ./*). Also chmod'ed it to permission 777 (chmod -R 777 ./*).

Same bug as addressed here, https://github.com/Codiad/Codiad/issues/637 , could not fix it on my CentOS machine with the posted 'solutions'. Debian and Ubuntu work fine.

**Comment by lovelycuppatea** [comment]
is selinux in permissive, enforcing or disabled state?

**Comment by pixelstudioro** [comment]
i have the same problem, centos 6.6 + codiad v2.5.1 when i save the file first i got error "file cannot be save" and the file on server is empty , when i want to save second time than i got the alert popup than if i press cancel and save again the file is saved.
i can set up and demo for testing

**Comment by ihaohu** [comment]
I got similar error.

The way I got this resolved.

Using chrome inspector to look at the error/warning of the PHP AJAX return.
My case was due to mbstring module was missing. 

good luck
