### ISSUE TITLE
Syntax error with php Nowdoc

### ISSUE THREAD

**Issue by pandiloko** [Codiad/Codiad#747]
The following code shows a syntax error in Codiad:
```php
echo <<<'EOT'
<p>html or javascript or any desired output</p>
EOT;
```
Furthermore, ```echo <<< 'EOT'``` or ```echo <<< EOT``` (note extra space) are also valid but text is not colored as string, which I think is actually really nice bug/feature as I find easier to read code when it's not all green colored. 

Note: [nowdocs] (http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc)

**Comment by daeks** [comment]
see ace issue for further tracking of this
