### ISSUE TITLE
feature request: touch template

### ISSUE THREAD

**Issue by lovelycuppatea** [Codiad/Codiad#750]
would it possible to make a version of the default theme to support touch?
the single/double click on the files don't map to a touch of it, looks like this is the only problem to use codiad on my tablet.

Something like Touche:
http://benhowdle.im/touche/
https://github.com/benhowdle89/touche

might be a quick fix for it, the below works for me

add:
```<script type="text/javascript" src="js/touche.min.js"></script>```
to index.php on line 90
after uploading to js folder

change filemanager init to use .on('click' ###) instead of .live() on line 86
and commenting out the filemanager single/double click check if
```
.on('click', function() { // Open or Expand
                    //if (codiad.editor.settings.fileManagerTrigger) {
                      if ($(this)
                          .hasClass('directory')) {
                          _this.index($(this)
                              .attr('data-path'));
                      } else {
                          _this.openFile($(this)
                              .attr('data-path'));
                      }
                      if (!$(this).parent().children("span").hasClass('none')) {
                          if ($(this).parent().children("span").hasClass('plus')) {
                              $(this).parent().children("span").removeClass('plus')
                              $(this).parent().children("span").addClass('minus');
                          } else {
                              $(this).parent().children("span").removeClass('minus')
                              $(this).parent().children("span").addClass('plus');
                          }
                      }
                    //}
                })
```

oh, live() appears to be depreciated btw: http://api.jquery.com/live/

hope this helps, means i can use codiad when on the move once i get the ftp/scp bits working on my host.

**Comment by daeks** [comment]
Please push in changes by a pull request
