### ISSUE TITLE
Terminal, and python. EOF error. Auto enter when I try run my script.

### ISSUE THREAD

**Issue by SzateX** [Codiad/Codiad#755]
Hello. I'm find the Isue in Terminal Plugin installed from Marketplace. I can sign in to it. I can run script. But when i try in script read data from keyboard (like raw_input) and I can't. Python show me EOF Error. It's means, the input is empty. I think, the Codiac Terminal auto "hit enter" when user is ask to input data from keyboard.

**Comment by daeks** [comment]
Please forward this issue to the plugin repository: https://github.com/Fluidbyte/Codiad-Terminal
