### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by Lord-Y** [Codiad/Codiad#757]
Hi all,

Codiad is really good but actually, his big issue is about word wrap. It's actually not really working. I have always to go to setting and click on wrap lines because even if it's set b default. I always have an overflow bar to scroll ....

It should be nice if it can be fixed :)

Thx guys.

**Comment by daeks** [comment]
have you tried to clear your browser cache?

**Comment by Lord-Y** [comment]
Yes I cleared it and also cleared codiad cache on my own server just in case but I still have the same issue.
