### ISSUE TITLE
Marketplace hanging while installing

### ISSUE THREAD

**Issue by nickbe** [Codiad/Codiad#766]
When installing a plugin the "Installing..." popup stays open indefintely. After that the plugin itself can be found in the plugins folder, but does not appear as registered plugin, not can it be used. 
Did I miss something here?

**Comment by daeks** [comment]
with "plugin itself can be found" do you mean it was installed completly (with content inside) or just an empty folder?

**Comment by nickbe** [comment]
The plugin folder seems ok (completely with contents) so write access seems to be ok. 

But a plugin.php inside the data folder is not created (nor modified if I create it by hand).

I had the exact same problem under windows first. Then I thought this might be windows specific and installed codiad on a linux server (PHP 5.4.x stable). 

I put codiad in the root folder of a domain as well as inside a subfolder /codiad. The same effect. Every time the plugin installation hangs. The "conpletePlud" plugin does nothing. No plugin shows in the sidebar under plugins. 

Also I tried the current release as well as the nightly github version.

**Comment by daeks** [comment]
There will be no plugin.php containing any plugin.  
As long as the plugin folder exists with its plugin.json it will be loaded automatically into Codiad. 

Which plugin did you tried? "conpletePlud" sounds not like a known one. 

PS: such problems are undepended from the OS.

**Comment by nickbe** [comment]
The installation hangs with ALL plugins from the marketplace. 
We tried it on a completely different web server today. Same effect here.

**Comment by daeks** [comment]
hmm, I have tried on a fresh installation (win + ubuntu, each with apache 2.4 and php 5.6.x) without any problem. could you check in browser's log if there is thrown any kind of javascript error?

**Comment by daeks** [comment]
hmm, I have tried on a fresh installation (win + ubuntu, each with apache 2.4 and php 5.6.x) without any problem. 
Could you check in browser's log if there is thrown any kind of javascript error? 
If not, could you check the reponse of ```http://<yourdomain>/codiad/components/market/controller.php?action=install&type=plugins&name=<pluginname>&repo=<repourl>``` ? 
It should state something like ```{"status":"success","data":null}```

**Comment by nickbe** [comment]
When installing I get this response: Example: "beautify" plugin

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Am Mi., Febr. 18, 2015 07:02 schrieb daeks : hmm, I have tried on a fresh installation (win + ubuntu, each with apache 2.4 and php 5.6.x) without any problem. could you check in browser's log if there is thrown any kind of javascript error?

**Comment by nickbe** [comment]
Now we're getting somewhere:

Strict Standards: Only variables should be passed by reference in /kunden/blue-group.de/webseiten/codiad/codiad/components/market/class.market.php on line 205
 {"status":"success","data":null}
Am Mi., Febr. 18, 2015 07:06 schrieb daeks : hmm, I have tried on a fresh installation (win + ubuntu, each with apache 2.4 and php 5.6.x) without any problem. 
 Could you check in browser's log if there is thrown any kind of javascript error? 
 If not, could you check the reponse of http:///codiad/components/market/controller.php?action=install&type=plugins&name= (http:///codiad/components/market/controller.php?action=install&type=plugins&name=)&repo= ? 
 It should state something like {"status":"success","data":null}

**Comment by daeks** [comment]
yeah this looks much better. I assume that your installation is set to ```error_reporting = E_ALL``` ?
you could try to avoid this warning by using ```error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT``` 

In the meanwhile I will have a look how solve that

**Comment by daeks** [comment]
Please check with latest nightly. I assume that there might be some other places as well, so I would really appreciate any finding.

**Comment by nickbe** [comment]
Yes it's set this way, but we also currently need the setting.
Am Mi., Febr. 18, 2015 20:02 schrieb daeks : yeah this looks much better. I assume that your installation is set to error_reporting = E_ALL ?
 you could try to avoid this warning by using error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT 
 In the meanwhile I will have a look how solve that

**Comment by nickbe** [comment]
Update to nightly:
 Warning: rmdir(/www/blue-group.de/webseiten/codiad/codiad): Directory not empty in /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php on line 26
 Warning: mkdir(): File exists in /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php on line 17
 Warning: mkdir(): File exists in /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php on line 17
 Warning: mkdir(): File exists in /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php on line 17
 Warning: rmdir(/www/blue-group.de/webseiten/codiad/codiad/backup): Directory not empty in /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php on line 57
 Warning: Cannot modify header information - headers already sent by (output started at /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php:26) in /kunden/blue-group.de/webseiten/codiad/codiad/27d83a87d5d161b0f41cf8cdea726bcdfd492d57.php on line 60
Reloaded the page:
Not my version is given as: 27d83a87d5d161b0f41cf8cdea726bcdfd492d57
Am Mi., Febr. 18, 2015 20:12 schrieb daeks : Please check with latest nightly. I assume that there might be some other places as well, so I would really appreciate any finding.

**Comment by nickbe** [comment]
Since the DocHub site is down the plugin doesn't much sense anymore I guess.
Is there a replacement?
Am Mi., Febr. 18, 2015 20:12 schrieb daeks : Please check with latest nightly. I assume that there might be some other places as well, so I would really appreciate any finding.

**Comment by nickbe** [comment]
btw. another problem I encountered:
If I copy an existing workspace folder into a fresh codiad installation the projects/folders are not recognized.
I think codiad should have a way to re-accept these project folders.

Cheers
Nick
Am Mi., Febr. 18, 2015 20:12 schrieb daeks : Please check with latest nightly. I assume that there might be some other places as well, so I would really appreciate any finding.

**Comment by daeks** [comment]
Please dont mixup issues with several topics. Regarding your questions:

- First looks like Autoupdate plugin, I have tried it on my machine without any problem, but I will have a look into it.
- Second: please ask plugin author directly. All plugins except from Collaborative are from third party authors. 
- Third: Thats not really a problem, all projects are organized by the administration panel. You have to create them first and then move its content into them .
