### ISSUE TITLE
Can't open index.php files

### ISSUE THREAD

**Issue by megadr01d** [Codiad/Codiad#769]
I haven't updated Codiad in some time (last version I was using was probably 2.4.2 or 2.4.3).
Having updated to the latest 2.5.3 I can no longer open `index.php` files. I get a warning red pop-up saying "Not A File". All other files including the `php` extension but with filenames other than `index` open correctly.
Tried with no plugins installed, same behavior.

How can I troubleshoot this?

**Comment by daeks** [comment]
do you have installed any kind of plugins installed? I tried it on a fresh installation without any problem. You could also try to clear your browser's cache

**Comment by megadr01d** [comment]
You're right and I'm sorry to have bother. I always forget to empty the browser's cache when troubleshooting.

Apparently it's because of a root `.htaccess` rewrite rule I always had to remove `/index.php` from my URLs and didn't cause any problems before because I had another `.htaccess` file in Codiad's folder to rewrite a subdomain for it, which overruled the root `.htaccess` file.

Since I recently removed Codiad's `.htaccess` and moved the subdomain rewrite to the root file, the `/index.php` started kicking in. Mystery solved, thanks Daeks.
