### ISSUE TITLE
Single-click Filemanager trigger and open 2 folders consecutively

### ISSUE THREAD

**Issue by megadr01d** [Codiad/Codiad#770]
Single clicking for the filemanager tree is currently broken, tested with Chrome and Firefox, caches cleaned, no plugins. It only responds to double clicking whatever option is selected.

Second issue is a long standing one. If you try to expand 2 folders consecutively, their contents overlap and show all together as they were inside the last clicked folder while the first clicked folder remains with the progress spinner.

But Codiad is known to have some quirks on specific server configurations so I might be the oddball here.

**Comment by daeks** [comment]
I have tried both on a fresh installation (apache 2.4 + 5.6.x) on a winnt based system with latest chrome x64 without any issue. could you check chrome's console log if there is any kind of error displayed?

**Comment by megadr01d** [comment]
Nothing in the Console and no open events in the Network tab. Chrome 40.0.2214.115 m, not sure what Apache but suspect 2.4 and PHP 5.5.20. Tried a fresh install, both abspath and relative project. Can't even single-click to switch projects. Nevermind it too much, Daeks, I'll try it again in a couple of versions. I keep coming back to it =)

**Comment by daeks** [comment]
Please reopen if required

**Comment by daeks** [comment]
regarding first issue ref. to https://github.com/Codiad/Codiad/commit/c04414a9dcb631119a28db416ed5d7f59bc8c09e

**Comment by megadr01d** [comment]
Confirmed to work :+1: 
Thanks Daeks.
