### ISSUE TITLE
Small improvement suggestion - open file directly on create

### ISSUE THREAD

**Issue by smolinari** [Codiad/Codiad#773]
What I'd like to see is when a new file is created in the explorer, then it should open up in the editor immediately after being created. Any IDE does this normally.

Scott

**Comment by daeks** [comment]
https://github.com/Codiad/Codiad/commit/d2554ed8debdf2b720ffc2047f8be3ade0252652

**Comment by smolinari** [comment]
Excellent and such an easy change too. Thank you!

Scott
