### ISSUE TITLE
cannot loggin to my newly created project

### ISSUE THREAD

**Issue by a1exus** [Codiad/Codiad#774]
I'm trying out Codiad 2.5.4 in my environment:

```
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)
# uname -a
Linux X 2.6.32-504.8.1.el6.x86_64 #1 SMP Fri Dec 19 12:09:25 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
# rpm -q httpd php
httpd-2.2.15-39.el6.x86_64
php-5.3.3-40.el6_6.x86_64
# 
```

I followed Installation: Codiad/Codiad Wiki - https://github.com/Codiad/Codiad/wiki/Installation

I then created a project and when I try to login, Codiad is not taking my username and password, if I type in wrong password, it tells me that information: "Incorrect Username or Password"

I'm not seeing anything in logs, what else can I try to get it going?

**Comment by daeks** [comment]
could you check the content of your data directory? What is in it? Whats the content of these files?
