### ISSUE TITLE
PHP 5.6 Json Issue

### ISSUE THREAD

**Issue by dcrdev** [Codiad/Codiad#775]
Just upgraded to PHP 5.6 and am getting a an error which is preventing the marketplace from working within codiad (on the latest nightly).

I get this: Warning: Invalid argument supplied for foreach() in /storage/.kodi/userdata/addon_data/service.web.lamp/www/htdocs/codiad/components/market/class.market.php on line 73

On further inspection this appears to be caused by jsondecode being called within the loop.

**Comment by daeks** [comment]
which os do you have? i am running one development machine with apache 2.4 and php 5.6.x without any problem

**Comment by smolinari** [comment]
I am also running Codiad on a development VM but with Nginx and php 5.6.4 and the marketplace works without any issues.

Scott

**Comment by dcrdev** [comment]
Hmm strange, this is on Tiny Core Linux running Apache 2.4. I still haven't figured this out but like I said it runs fine on a build exactly the same with 5.5.x . Are there any requirements that might not be getting built with PHP 5.6 - that aren't on the installation documentation?

**Comment by daeks** [comment]
You could try to check if this file exist on your machine ```DATA/cache/market.current``` as this one is used for the menioned line 73

**Comment by dcrdev** [comment]
I'm assuming this is meant to be the cached json array to loop through? If that's the case mine exists but is empty?

**Comment by daeks** [comment]
yes thats correct. If it is empty you chould check if allow_url_fopen is set to 1. 

http://php.net/manual/en/filesystem.configuration.php

**Comment by dcrdev** [comment]
I'll try that -

It's not a json issue - I manually grabbed the extract and populated those files which got the plugins displaying. Must be an fopen issue. Further examination of my apache logs reveals this: "php_network_getaddresses: gethostbyname failed. errno=11" which suggests a dns error (although I'm able to ping the marketplace domain fine).

**Comment by daeks** [comment]
hmm keep us updated - you could also replace the market url in your config.php with an IP adress

**Comment by Hambrook** [comment]
It's probably related to PHP5.6's new JSON validation requirements regarding boolean values.

http://php.net/manual/en/function.json-decode.php

**Comment by Hambrook** [comment]
Maybe not, my bad.

**Comment by MasterFrese** [comment]
same problem here "Warning: Invalid argument supplied for foreach() in *********\components\market\class.market.php on line 73
Codiad Marketplace" running on windows 7 xampp newest version with PHP 5.6

**Comment by dcrdev** [comment]
This happened to me for a number of reasons:
1) The latest version of Apache throws a fit when you don't specify the servername directive - this was causing httpd to bind to it's own internal IP and thus prevented certain types of outbound connections.
2) The lack of outbound connection support mean't that codiad created empty cache files (DATA/cache/market.*).
3) class.market.php looks for these cache files and if they exist and are within a tolerable time limit, loops through each json string in the array. The blank cache files causes this to fail.

The solution on my part was to delete the cache files and set the servername directive in Apache - then it was just a case of accessing the marketplace via Codiad once more, and voila! populated cache files and a working setup.

**Comment by daeks** [comment]
So from my point of view, it would be good to add some kind of "internet check" before using marketplace to be sure that a connection to the marketplace could be made
