### ISSUE TITLE
External Auth bug? - not staying logged in

### ISSUE THREAD

**Issue by Korynkai** [Codiad/Codiad#777]
This occurs when I'm using External Auth, specifically LDAP... However, I'm not sure if the issue lies within my LDAP External Auth plugin, Codiad itself or even PHP's LDAP implementation itself, however the issue started to occur spontaneously when I logged in to Codiad on a different machine while a session was still active on the machine I am currently using. Previously when I had done this, I had noticed a few quirks (i.e. skewing of text), however, I had never had any problems as severe as this. Now Codiad logs me out less than 10 second after I logged in...

Also, when I logged in with default authentication under the same user (which worked perfectly fine), I had noticed the file I was editing, which I know I had saved, was completely wiped. Codiad was working perfectly fine before this started and the system environment had not changed before the problem occurred.... 

Already tried the solutions within #442 with no luck... Also tried updating Codiad and the system in an attempt to resolve the problem.. Tried clearing caches, restarting apache and literally anything else I could think of to no avail. EDIT: I do realize #442 does not involve logging out every 10 seconds, but had wondered if it could be related..

You can find my LDAP External Auth plugin here: https://github.com/QMXTech/Codiad-LDAPExternalAuth/blob/master/ldap.php
Please do note that I did write this myself a while back and it has been working fine since then, up until yesterday when this started occurring.

The only relevant (apache) log entry is here: https://gist.github.com/Korynkai/04a62580bcb2d993cf84

It tells me there's an issue with calling ldap_compare, however I tried to change this call extensively (trying to get its parameter data in different ways) also to no avail... The undefined index entry is irrelevant and is simply trying to set the session project variable when it is empty (a simple "isset" check I initially forgot but resolved while trying to fix this).

PHP: 5.5.9-1ubuntu4.6
Codiad: Tested with 2.5.3 & 2.5.4

Any help would be greatly appreciated. This breakage is taking up productivity time within our group and we'd like to fix this ASAP. Thank you.

**Comment by Korynkai** [comment]
Fixed that issue in my implementation, turns out I had a major security vulnerability going on anyway, but it still does not solve this problem, still getting the same instantaneous logout...

**Comment by daeks** [comment]
Did you tried it without any kind of installed plugin? which plugins do you have installed?

**Comment by Korynkai** [comment]
I actually just reproduced this on a test machine. Steps taken:
* Create a fresh install of Codiad on a clean LAP/LNP environment (in this case on a dedicated VM server using a barebones Ubuntu 14.04 image) performing all necessary actions and making all necessary configuration modifications.
* Create user 'test' on Codiad with project 'test'.
* Log out and back in and wait for about a minute to note the behavior (as a control test). Notice the webpage refresh rate (or lack thereof).
* Create the External Auth bridge described under "Setup" here: https://github.com/Codiad/Codiad/wiki/External-Auth and place its `define` directive in config.php
* Log out and back in and wait for about a minute to note the behavior. Notice the webpage refresh rate (or lack thereof). If this _is_ a bug, the webpage will continuously refresh at an interval of about 10 seconds.

No plugins installed whatsoever on the test machine.

**Comment by daeks** [comment]
```also wiping data/users.php in favor of the External Auth environment (make a backup if you need to, obviously).```

this file should not be deleted

**Comment by Korynkai** [comment]
Regardless, shouldn't it be emptied to this state?:
`<?php/*|[]|*/?>`
Otherwise its contents actually interfere with login... I had noticed this when I first implemented LDAP External Auth. Specifically I used a different password for my initial user and noticed that, not only would the initial password still work but it seemed as if External Auth was even overridden by basic auth...

**Comment by Korynkai** [comment]
Huh, I'll be damned... After some testing, apparently I was wrong, if anything, the password and nothing else should be wiped (though the old unmodified fie should be kept as a backup in case of external auth problems)... It seems to be working properly now, however this still does not explain why it *suddenly* happened to me when nothing in that context whatsoever changed before this issue started happening.

Also, a question: Will external auth automatically generate a user if it does not exist? Or does the external auth developer need to write such functionality in?

**Comment by daeks** [comment]
Normally this should not happen, but it might be possible that we have "fixed" something compared to your old version. New user will currently not be added automatically and yes they are required to be in, but users.php could be maintained by the external auth bridge as well. 

https://github.com/Codiad/Codiad/blob/master/components/user/class.user.php#L70

**Comment by Korynkai** [comment]
Ahh I see, I'll have to write that in then. Thank you very much Daeks, you've been a great help!

**Comment by daeks** [comment]
one quick note: feel free to put your repo to our wiki if you want to share your ldap auth

**Comment by Korynkai** [comment]
@daeks, where within the wiki would you prefer I put said repo?

**Comment by daeks** [comment]
At "Examples" on https://github.com/Codiad/Codiad/wiki/External-Auth

**Comment by Korynkai** [comment]
If you didn't already notice, I added it earlier today. Thanks again Daeks!
