### ISSUE TITLE
Installation Problem (No such file)

### ISSUE THREAD

**Issue by zbriggs** [Codiad/Codiad#782]
Problem occurred on a Windows 7 system using WAMP server. Started free on a CentOS LAMP server and got the same results. Attempted to debug issue and was not very successful. Its having some sort of trouble accepting the path data from the variable.

=====ERRORS=====
Warning: include(/ide/languages/en.php): failed to open stream: No such file or directory in /home/zbriggs/public_html/ide/common.php on line 95
Warning: include(): Failed opening '/ide/languages/en.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/zbriggs/public_html/ide/common.php on line 95
Warning: file_get_contents(/ide/components/filemanager/context_menu.json): failed to open stream: No such file or directory in /home/zbriggs/public_html/ide/index.php on line 6
Warning: file_get_contents(/ide/components/right_bar.json): failed to open stream: No such file or directory in /home/zbriggs/public_html/ide/index.php on line 10
Warning: scandir(/ide/components): failed to open dir: No such file or directory in /home/zbriggs/public_html/ide/common.php on line 105
Warning: scandir(): (errno 2): No such file or directory in /home/zbriggs/public_html/ide/common.php on line 105
Warning: Invalid argument supplied for foreach() in /home/zbriggs/public_html/ide/common.php on line 106
Warning: scandir(/ide/plugins): failed to open dir: No such file or directory in /home/zbriggs/public_html/ide/common.php on line 105
Warning: scandir(): (errno 2): No such file or directory in /home/zbriggs/public_html/ide/common.php on line 105
Warning: Invalid argument supplied for foreach() in /home/zbriggs/public_html/ide/common.php on line 106
Warning: scandir(/ide/themes): failed to open dir: No such file or directory in /home/zbriggs/public_html/ide/common.php on line 105
Warning: scandir(): (errno 2): No such file or directory in /home/zbriggs/public_html/ide/common.php on line 105
Warning: Invalid argument supplied for foreach() in /home/zbriggs/public_html/ide/common.php on line 106

=======CONFIG=======
<?php

/*
*  Copyright (c) Codiad & Kent Safranski (codiad.com), distributed
*  as-is and without warranty under the MIT License. See
*  [root]/license.txt for more. This information must remain intact.
*/

//////////////////////////////////////////////////////////////////
// CONFIG
//////////////////////////////////////////////////////////////////

// PATH TO CODIAD
define("BASE_PATH", "/ide");

// BASE URL TO CODIAD (without trailing slash)
define("BASE_URL", "zachbriggs.name");

// THEME : default, modern or clear (look at /themes)
define("THEME", "default");

// ABSOLUTE PATH
define("WHITEPATHS", BASE_PATH . ",/home/zbriggs/public_html/ide");

// SESSIONS (e.g. 7200)
$cookie_lifetime = "0";

// TIMEZONE
date_default_timezone_set("America/Chicago");

// External Authentification
//define("AUTH_PATH", "/path/to/customauth.php");

//////////////////////////////////////////////////////////////////
// ** DO NOT EDIT CONFIG BELOW **
//////////////////////////////////////////////////////////////////

// PATHS
define("COMPONENTS", BASE_PATH . "/components");
define("PLUGINS", BASE_PATH . "/plugins");
define("THEMES", BASE_PATH . "/themes");
define("DATA", BASE_PATH . "/data");
define("WORKSPACE", BASE_PATH . "/workspace");

// URLS
define("WSURL", BASE_URL . "/workspace");

// Marketplace
//define("MARKETURL", "http://market.codiad.com/json");

// Update Check
//define("UPDATEURL", "http://update.codiad.com/?v={VER}&o={OS}&p={PHP}&w={WEB}&a={ACT}");
//define("ARCHIVEURL", "https://github.com/Codiad/Codiad/archive/master.zip");
//define("COMMITURL", "https://api.github.com/repos/Codiad/Codiad/commits");

?>

**Comment by daeks** [comment]
please search in the other issues, centos and wamp has difficulties on these systems

**Comment by zbriggs** [comment]
Then what good is this? The majority of web servers are CentOS/RHEL based.

**Comment by zbriggs** [comment]
I suppose you are also going to tell me it has issues with Debian? Cause I have the same errors.

**Comment by daeks** [comment]
I have only put some small notification from my mobile device that there are known problems with wamp and centos, but second look at the error description it seems to be a configuration issue on your end:

Warning: include(/ide/languages/en.php): failed to open stream: No such file or directory in /home/zbriggs/public_html/ide/common.php on line 95

define("BASE_PATH", "/ide");

which should be 

define("BASE_PATH", "/home/zbriggs/public_html/ide");

**Comment by zbriggs** [comment]
Below are the lines from the config example. Note that you have two entries for the path. Says base path which in most applications is the path relative to the domain root. Additionally it provides no more information than "/path/to/codiad". Below that you have a separate entry that requests the Absolute Path. It has the example provided of "/home" which leads one to believe that this will be the full path from operating system root. This is pretty normal for most PHP applications. Based on your response above and that it did solve the problem you are correct. Both are actually looking for the full path. This leads me to ask why this is even two variables and why the instructions do not call this out more clearly.

======EXAMPLE CONFIG=========
// PATH TO CODIAD
define("BASE_PATH", "/path/to/codiad");

// BASE URL TO CODIAD (without trailing slash)
define("BASE_URL", "domain.tld");

// THEME : default, modern or clear (look at /themes)
define("THEME", "default");

// ABSOLUTE PATH
define("WHITEPATHS", BASE_PATH . ",/home");

**Comment by daeks** [comment]
glad to hear that it works now. Normally this paths are set during the automated installation, but you are correct that could be more clear for manual installations. I will add more information to the example config
