### ISSUE TITLE
Check for required modules during installation. 

### ISSUE THREAD

**Issue by daeks** [Codiad/Codiad#783]
related to. https://github.com/Codiad/Codiad/issues/637 and https://github.com/Codiad/Codiad/issues/746

it should be checked for:

zip
openssl
mbstring

and print a warning

**Comment by evertton** [comment]
I think to use the function `extension_loaded` to check whether an extension is enabled. It has some mockup for how this feature should be displayed?

**Comment by evertton** [comment]
What do you think?
![2015-05-02 17-48-15 codiad - mozilla firefox 2](https://cloud.githubusercontent.com/assets/2022984/7442738/a81ad09c-f0f3-11e4-9644-d3a20ebf5044.png)

**Comment by daeks** [comment]
looks good
