### ISSUE TITLE
"Right Side" drawer cannot be resized by plugin

### ISSUE THREAD

**Issue by ghost** [Codiad/Codiad#794]
If a plugin would like to resize the right bar with the plugin style (screen.css), the real size is not used when this toolbar is open/closed again.
This is due to static size in some js code.

Someone already noticed this issue while using one of my plugin (https://github.com/Smartlug/Codiad-Outline/issues/2)

Best way would be to be able to resize the right toolbar but as it's more complicate to code, could-you simply modify sidebar.js (this is really a minor modification) ?

To solve it, you just need to modify codiad/js/sidebar.js and 
replace line 203 :
```
		$('#sb-right')
                .animate({
                    'right': '-190px'
                }, 300, 'easeOutQuart');
```
by
```
		var sbarWidthR = $("#sb-right").width();
		$('#sb-right')
                .animate({
                    'right': '-'+(sbarWidthR-10)+'px'
                }, 300, 'easeOutQuart');
```

**Comment by daeks** [comment]
feel free to open a pull request for it

**Comment by daeks** [comment]
https://github.com/Codiad/Codiad/pull/795
