### ISSUE TITLE
Types of responses

### ISSUE THREAD

**Issue by smolinari** [Codiad/Codiad#800]
Hi,

I was wondering, is there reasoning and/ or some rules as to when and why Codiad receives different types of responses and not just JSON all the time?

Scott

**Comment by daeks** [comment]
no there is no common reason, maybe depending on the specific case

**Comment by smolinari** [comment]
Ok. Thanks for the quick reply. This makes my porting Codiad to a Symfony bundle a bit more  complicated. Has anyone considered standardizing the API?

While I have you, :-) what is the reason for constantly polling the server, to see if the user is a valid user? 

Scott

**Comment by daeks** [comment]
currently nobody is doing that with the API, but I am happy to see usefull pull requests for that.
Polling is for keeping the session alive also if you are away from the keyboard for a longer time to prevent the potential loss of unsaved changes.

**Comment by smolinari** [comment]
Ah, ok on the polling. 

As for standardizing the API. I wish I had the time to do both mx project and update Codiad in parallel, but I don't. Sorry. You probably don't want me messing up Codiad either. LOL!

Thanks for your help anyway.

Scott
