### ISSUE TITLE
Languages supported

### ISSUE THREAD

**Issue by mvmaasakkers** [Codiad/Codiad#809]
I couldn't find a list with all supported programming languages (the homepage suggested 40+, but those could be spoken languages supported :P). It would be helpful for me to make educated choices about which Cloud IDE to start using if could you provide such a list? Or am I just short-sighted and missing it (which is also a very real possibility)?

**Comment by smolinari** [comment]
The underlying editor is ACE, which allows a lot of extensibility, when it comes to code highlighting.

http://ace.c9.io/#nav=higlighter

To see the available languages supported by Codiad, you can use the demo.

http://demo.codiad.com/

At the bottom of the editor next to "Split", you'll see an icon with four dots. Click on it and that opens up the syntax highlighting chooser and shows the supported languages.

Scott

**Comment by daeks** [comment]
I know it is a bit too programmtic, but currently there is no real "external" list for supported languages.

https://github.com/Codiad/Codiad/blob/master/components/fileext_textmode/class.fileextension_textmode.php#L49

**Comment by mvmaasakkers** [comment]
Thanks!
