### ISSUE TITLE
Right Sidebar Trigger

### ISSUE THREAD

**Issue by megadr01d** [Codiad/Codiad#813]
On my end, the right sidebar trigger setting was never applied between sessions, since the earlier Codiad versions.

I set it to "Click", the setting is saved across sessions but when logging in Codiad, it always shows up on "Hover", the first time. So I have to go into settings every time and just save again so the "Click" option is re-applied.

Suddenly in v2.6.0 it got magically fixed. The Right Sidebar no longer triggered on hover the first time I logged in, If I had set it to "Click". So the setting was getting correctly saved and read at login.

And from v2.6.1 onwards, it got broken again and that setting was longer applied on login, unless it was saved again.

So, what changed in v2.6.0 code that made it work for the first time?

**Comment by daeks** [comment]
https://github.com/Codiad/Codiad/commits/master/js/sidebars.js

**Comment by megadr01d** [comment]
I found out it's the local storage implementation. It's not just the rightbar, the leftbar also doesn't get its settings read at login. Thanks.
