### ISSUE TITLE
mode preview

### ISSUE THREAD

**Issue by djthoz91** [Codiad/Codiad#816]
Bonjour,

je viens d'installer codiad sur mon serveur web. Il fonctionne tres bien mais je n'arrive pas à résoudre le mode preview. Lorsque je clique sur le bouton preview. j'ai cette page web qui s'ouvre sur mon navigateur https://yyyyyy.com/codiad/workspace//var/www/codiad/workspace/mon_projet_yyyy/test.html.

Comment faire pour pouvoir afficher https://yyyyyy.com/codiad/workspace/mon_projet_yyyy/test.html.

merci

**Comment by daeks** [comment]
english pls

**Comment by djthoz91** [comment]
Hello,

I just installed on my web server codiad . It works very well but I can not seem to solve the preview mode. When I click on the preview button. I have this web page that opens on my https://yyyyyy.com/codiad/workspace//var/www/codiad/workspace/mon_projet_yyyy/test.html browser.

How to display https://yyyyyy.com/codiad/workspace/mon_projet_yyyy/test.html .

thank you

**Comment by daeks** [comment]
It looks like you have misconfigured WSURL. 

https://github.com/Codiad/Codiad/blob/master/config.example.php#L49

**Comment by nickbe** [comment]
For me there's no preview button at all. Where do I find this?
