### ISSUE TITLE
Integration with FlySystem

### ISSUE THREAD

**Issue by cheiff** [Codiad/Codiad#819]
Hi,

how difficult or  would be even possible to integrate codiad with FlySystem?
http://flysystem.thephpleague.com/
The idea would be to be able to work directly on remote projects, such as other online editors using SFTP, etc.
Any hint of where could I start? Could it be as a plugin or should it be "hard coded" into the system?

Thank you, kind regards.

**Comment by daeks** [comment]
Currently it is hard to implement cause the filemanager is based on local file system. Maybe it is possible to include that as "fake folder" to codiad's workspace?

**Comment by cheiff** [comment]
Thanks for answering. 
I have solved it "temporarirly" by using sshfs. It works very good. If I have time in the near future, I'll try to investigate that "fake folder" concept.
Thank you, regards

**Comment by daeks** [comment]
Feel free to share your findings in the [wiki](https://github.com/Codiad/Codiad/wiki) as tutorial for others.
