### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by gregor160300** [Codiad/Codiad#822]
Hello I found Codiad yesterday and was pretty impressed by how fine it works, the only problem is that it doesn't have the ability to compile programs, which is one of the main functions of an IDE.
So I hope it will be added soon

**Comment by daeks** [comment]
Hi, have a look at the marketplace http://market.codiad.com/ . Personally i prefer my own plugin Macro, which allows to define custom shell scripts like compiling stuff

**Comment by gregor160300** [comment]
Thanks that will probably work, just for the record compiling a c++ program would be like:
g++ %file%

**Comment by nerodark** [comment]
im using codiad as a frontend for a compiling platform http://kodera.tk
contact me if you want hints.

**Comment by daeks** [comment]
@gregor160300 if you use that macro plugin, new commands will be attached to defined level in the context menu or in the rightbar

**Comment by gregor160300** [comment]
@nerodark Your website is down, but if you could give me a email adress or something we could contact eachother, btw I am working on a complete new interface for codiad, I am still considering how it will eventually be posted like in a fork or no source just on my website.

**Comment by smolinari** [comment]
@gregor160300 - can you explain more about what you are doing? 

Scott

**Comment by gregor160300** [comment]
@smolinari I am redesigning the interface so it looks more attractive and is easier to use, also I will go with a flat design and put buttons on other places

**Comment by smolinari** [comment]
Sounds interesting. Are you also improving the interface, so that it is also completely standardized? Like all calls being RESTful?

Scott

**Comment by gregor160300** [comment]
I dont understand what you mean by restful, I will base colors and use on numix(nice and dark since most devs work at night bright colors hurt eyes), remove shadows they look ugly and then it will become a flat expreience sort of like android lollipop I have a idea for the placement of buttons and such but that will take some weeks to do so first the theme and then rebuild I will make a mock up now of the screen with placement of buttons and such

**Comment by gregor160300** [comment]
Here are my sketches I hope they are readable, colors are subject to change. 
![img_20150525_185136302](https://cloud.githubusercontent.com/assets/7871398/7800035/5f852f5c-030f-11e5-8881-3e47307d6e09.jpg)
![img_20150525_185138726](https://cloud.githubusercontent.com/assets/7871398/7800036/5f8667be-030f-11e5-8229-9f79ca6aa537.jpg)

From left to right top buttons are: settings, logout, load mega drive in filemanager*, load github in filemanager*, load google drive in filemanager*, to be assinged, compile*, run*, back arrow for tabs, tabs, next arrow for tabs, undo*, redo*, save, programming language.

In the left bottom there is a small terminal with ability to expand to fullscreen*

* Probably wont be able to make myself

**Comment by daeks** [comment]
feel free push changes in with a pullrequest

**Comment by smolinari** [comment]
Ok. You are working on just the UI design. I thought maybe you'd be also working on the interface with the server too. Nevermind.

**Comment by gregor160300** [comment]
![screenshot_2015-05-27_17-08-05](https://cloud.githubusercontent.com/assets/7871398/7839529/fecd9eb2-0492-11e5-93f8-b29d46bbcf53.png)

Wip but I would like to show you sort of what it is becoming with colors

**Comment by AlisPT** [comment]
neodark, I need your help with the run plugin, how did you implement it? I am trying to setup an IDE for home use based on codiad and compile/run is a must.

**Comment by nerodark** [comment]
the run plugin calls a single php file thats run a bash script thats contains a switch case for all languages that i support and then redirects the output to a file and to codiad.

if you want more info contact me at nerodark@hotmail.com
