### ISSUE TITLE
Adding extra quotation marks in php.

### ISSUE THREAD

**Issue by JOJOManLV** [Codiad/Codiad#824]
Hi...
I realy like your IDE, but i have found a bug who is annoying me.

So basicly it looks like that.

when you are typing in index.php text like <div class='testclass'></div> or something like that. It's automatically add one extra quotation mark, And when i try delete extra mark it's delete two quotation marks. How to fix this..? It's also happens on your DEMO site. But when you editing .html file everything is working fine.
So the problem is in .php when making simple html text.

image
![untitled](https://cloud.githubusercontent.com/assets/7753270/7944961/8197aaf8-0976-11e5-9e57-d8cf8e64ca29.png)

**Comment by daeks** [comment]
its working fine for me on the latest version.

![untitled](https://cloud.githubusercontent.com/assets/3989440/7953367/27867154-09c4-11e5-901e-8f78dc4719e7.png)

**Comment by JOJOManLV** [comment]
Hm.... Strange I try to use different browsers still the same problem.... I am little bit confused.

**Comment by daeks** [comment]
you could try to clear your browser's cache. Beside that it is hard to say as I cant reproduce it (Chrome 43.0.2357.81 m (64-bit), Win7)
