### ISSUE TITLE
Suggestion: Preview webpages within a codiad tab

### ISSUE THREAD

**Issue by TheJamaican** [Codiad/Codiad#827]
Is there a possibility for someone to create a plugin that facilitates the ability to preview webpages in tabs as they are being worked on - possibly through a frame that automatically refreshes when the source is saved?
As someone who uses Codiad in full-screen mode often it would be a big help.

**Comment by daeks** [comment]
that is currently not possible without a hugh rewrite of codiad's core components

**Comment by circuitbomb** [comment]
You don't necessarily need a plugin in Codiad to do this; instead either a browser plugin or toolchain component that facilitates live reload should suffice.

**Comment by TheJamaican** [comment]
Okay, thanks for the responses.
