### ISSUE TITLE
How to Create Errors/Warnings in Editor

### ISSUE THREAD

**Issue by dc-artemis** [Codiad/Codiad#834]
I'm writing a plugin and would like to, for the sake of simplicity, display an error on line 3 in the editor when a user clicks a button I have. Is this possible, or is it too far hidden in the Ace editor?

**Comment by daeks** [comment]
for example: https://jsfiddle.net/c8k45yw1/5/

**Comment by dc-artemis** [comment]
Thank you! Exactly what I was looking for. It wasn't on the GitHub wiki; are there other docs, or could I update the wiki, or is it purposely left out?

**Comment by dc-artemis** [comment]
Thank you!

For those who wander here with the same question:
codiad.editor.getActive().session.setAnnotations([...]);
