### ISSUE TITLE
Increase font size above 18px

### ISSUE THREAD

**Issue by jeroen-net** [Codiad/Codiad#840]
Hello Codiad developers,

How can I increase the size of the font in the texteditor above the 18px?
I need this because I want to use Codiad in a classroom environment.

Best wishes,

Jeroen-net

**Comment by daeks** [comment]
Currently it is limited to 18px, but it just can be changed in the code:

https://github.com/Codiad/Codiad/blob/master/components/settings/settings.editor.php#L52

**Comment by jeroen-net** [comment]
Perfect! I will add a few new lines!
Thank you very much!!
