### ISSUE TITLE
How to upload an entire directory structure in Codiad?

### ISSUE THREAD

**Issue by rafasashi** [Codiad/Codiad#842]
I am looking for a browser to server uploading feature for codiad.

The Codetransfer Plugin works well but only from server to server. 

Do you see any reliable alternatives to upload an entire directory structure in Codiad?

**Comment by daeks** [comment]
Best would be to use FTP as initial upload

**Comment by rafasashi** [comment]
Yes. I am thinking using the Codetransfer Plugin for that purpose. Making the left part pointing to C: instead of the workspace directory and connecting the Codiad Server via FTP. What do you think?

**Comment by rafasashi** [comment]
Another alternative would be to upload and unzip an archive.

**Comment by rafasashi** [comment]
To solve the problem I finally developed a plugin to unpack archives 

It works only with .zip for the moment.

https://github.com/rafasashi/Codiad-Archives

**Comment by daeks** [comment]
Which variables are you collecting here? Just asking because you unset them

https://github.com/rafasashi/Codiad-Archives/blob/master/controller.php#L14

**Comment by rafasashi** [comment]
I published the wrong piece of script :) it comes from a script reviewer I use to wrap external php modules into my environment.

**Comment by daeks** [comment]
yeah that looks better now :) I will test it later and add it to the marketplace

**Comment by beli3ver** [comment]
@daeks @rafasashi and me we update the plugin.
it supports rar und tar now.

**Comment by daeks** [comment]
i have added it to the marketplace
