### ISSUE TITLE
Multiple users and separate workspaces

### ISSUE THREAD

**Issue by dannysmc95** [Codiad/Codiad#845]
Hello,

I was wondering how, or if you are gonna make a way to have many users, but separate workspaces, but allowing users to have access to a shared set as well? So with the team I am with I would like to have personal workspaces for them, but have shared workspaces for everyone to access?

Cheers

**Comment by rafasashi** [comment]
I had the same requirements so I used `define("AUTH_PATH", "/path/to/AuthTemplate.php");` to implement a custom user authentication

**Wiki**
https://github.com/Codiad/Codiad/wiki/External-Auth

**Example**
https://gist.github.com/basteln3rk/4cab14ebd990e46efaef

then define the paths `WORKSPACE`, `WSURL` and `DATA` based on the user name

**Comment by dannysmc95** [comment]
Ahh I see, thank you for that, it's really useful, shall I have a more in-depth look!

**Comment by rafasashi** [comment]
I am also looking for a way to share the workspace. 

I have different alternatives in mind:

- Anonymous session with limited access
- Invitation with limited access

it doesn't have to be necessary implemented within Codiad or via a Plugin

What do you think?

**Comment by dannysmc95** [comment]
Well I found out you can give users access inside Codiad for certain workspaces, so I guess an admin can set users workspaces...?

Although I am looking at being able to share workspaces with another user, so you can send a share request to another member, then that member can accept to be able to view that workspace and edit on it etc. Which seems simple enough.

Yeah I thought about adding anonymous sessions but the problem I see with that is the code on my server can't be accessed by the outside, so I made a user called: Guest so they can use that to login and then they have limited workspaces that are set to them.
