### ISSUE TITLE
Bootstrap say Fuck you

### ISSUE THREAD

**Issue by otlet** [Codiad/Codiad#848]
Hi!

Problem? Really!

I open Bootstrap.css (original CSS) and i change something (neverming. Change space, everything) and now Codiad make Shit. Stop, crash. whatever... This doesnt work -_- Stop and Fuck myself :v

**Comment by daeks** [comment]
so what do you know expect from us? Please watch your language and post proper error descriptions

**Comment by otlet** [comment]
Sorry. Ok, i using Codiad in quick HTML edit, in front of client (via internet) and when i change something in big css file, Codiad crash and i cant log in, whatever. Codiad without plugins or themes. Only 3 account and some projects. It's problem with 2.6.* version only. When i having 2.5 and below, i dont having that problem.
