### ISSUE TITLE
Help with creating external authentication

### ISSUE THREAD

**Issue by dugite-code** [Codiad/Codiad#849]
So I am making an IMAP plugin for External Authentication: [Github of my IMAP plugin](https://github.com/dugite-code/codiad-imap_auth) and was wondering if anyone could point out the undoubtedly obvious mistake I am making:

Unfortunately I am stuck on the [Auto user creation part](https://github.com/dugite-code/codiad-imap_auth/blob/master/imap_auth.php#L48). I have looked at both [HTTP auth](https://gist.github.com/basteln3rk/4cab14ebd990e46efaef#file-codiad_http_auth-php-L12) and [LDAP auth](https://github.com/QMXTech/Codiad-LDAPExternalAuth/blob/master/ldap.php#L129) authentication methods and I THINK I am using it in the exact same manner.

The user is created just fine, it shows in the user list when I log in with an initial user I created before making the imap_auth plugin, but it comes up with `Incorrect username or password` and won't proceed with login.

**Comment by dugite-code** [comment]
AH-HA! I fixed it! I needed to send the verification token as from [LDAP auth](https://github.com/QMXTech/Codiad-LDAPExternalAuth/blob/master/ldap.php#L129). Amazing how a nights sleep shows you the way

```
// Respond by sending verification tokens on success.
echo formatJSEND( "success", array( 'username' => $User->username ) );
header( "Location: " . $_SERVER['PHP_SELF'] . "?action=verify" );
```

**Comment by daeks** [comment]
Great :) If you want we can add this plugin to our wiki to share it with other people

**Comment by dugite-code** [comment]
Yea sure, share away. Hope others find it useful
