### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by jfmxlgithub** [Codiad/Codiad#853]
Hello,

Im tryiing, but failing, to get codiad to work. I have installed nginx and followed the directions on the site.

nginx will serve an html page from /home/jfl/www but will not serve codiad from /home/jfl/www/codiad.jfmxl.sdf.org. The site is not on the internet. I put an entry for codiad.jfmxl.sdf.org in /etc/hosts. What I get at http://codiad.jfmxl.sdf.org according to firebug is 200 on the GET, but 

<html>
<head></head>
<body></body>
</html>

I have set up a

server {
    #listen   80; ## listen for ipv4; this line is default and implied
    #listen   [::]:80 default ipv6only=on; ## listen for ipv6

    root /home/jfl/www/codiad.jfmxl.sdf.org;
    index index.php index.html;

    # Make site accessible from http://localhost/
    server_name localhost codiad.jfmxl.sdf.org;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to index.html
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /404.html;

    # redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/www;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini [I do have, both cli and fpm]

        # With php5-cgi alone:
        #fastcgi_pass 127.0.0.1:9000;
        # With php5-fpm:
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
}

root@wsdeb:/home/jfl/www# ls -l /var/run/php5-fpm.sock 
srw-rw---- 1 www-data www-data 0 Aug  2 08:14 /var/run/php5-fpm.sock

root@wsdeb:/home/jfl/www# ps ax | grep php5
15554 ?        Ss     0:05 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)                    
29209 pts/2    S+     0:00 grep php5

I'm at a loss and so have come to bother you all. Thanks for any help you may give me.

**Comment by dugite-code** [comment]
Your root directory is in your home directory and usually the user www-data has no access to files in this directory so It could be a permissions issue. 

add the line `error_log       /var/log/nginx/error_mail.smwc.com.au_ssl.log;` above your root directory line then check `/var/log/nginx/error.log` to see if nginx will tell you anything (php5-fpm logs errors to the nginx log)

**Comment by jfmxlgithub** [comment]
Thanks. I did as you suggested, restarted nginx, hit http://codiad.jfmxl.sdf.org/ ... no difference.

I was running 

 tail -f  /var/log/nginx/error.log

at the same time ...

2015/08/03 11:19:56 [error] 28900#0: *23 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: codiad.jfmxl.sdf.org, request: "GET / HTTP/1.1", host: "codiad.jfmxl.sdf.org"
2015/08/03 11:19:57 [error] 28900#0: *24 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: codiad.jfmxl.sdf.org, request: "GET /favicon.ico HTTP/1.1", host: "codiad.jfmxl.sdf.org"
2015/08/03 11:19:57 [error] 28900#0: *25 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: codiad.jfmxl.sdf.org, request: "GET /favicon.ico HTTP/1.1", host: "codiad.jfmxl.sdf.org"
2015/08/03 11:20:19 [notice] 28924#0: signal process started
2015/08/03 12:13:59 [notice] 29223#0: signal process started
2015/08/03 15:37:40 [notice] 30278#0: signal process started

.. no new messages since the change and rstart at 15:37:40, but there were errors logged earlier about redirection to index.html which I hadn't seen before ... I stuck an index.html file in the directory and hit it again ... no difference.

So no change.

**Comment by jfmxlgithub** [comment]
I forgot to add that all the permissions are jfl.www-data ...

jfl@wsdeb:~$ ls -ld www
drwxr-xr-x 4 jfl www-data 4096 Aug  3 11:18 www
jfl@wsdeb:~$ ls -l www
total 12
drwxrwxr-x 10 jfl www-data 4096 Aug  3 15:40 codiad.jfmxl.sdf.org
drwxr-xr-x  2 jfl www-data 4096 Jul 29 21:32 html
-rw-r--r--  1 jfl www-data  158 Aug  2 09:51 index.html
jfl@wsdeb:~$ ls -l www/codiad.jfmxl.sdf.org/
total 132
-rwxr-xr-x  1 jfl www-data   413 Jun  3 03:34 AUTHORS.txt
-rw-r--r--  1 jfl www-data   456 Jun  3 03:34 build.xml
-rw-r--r--  1 jfl www-data 11810 Jun  3 03:34 common.php
drwxr-xr-x 17 jfl www-data  4096 Jun  3 03:34 components
-rw-r--r--  1 jfl www-data  1181 Jun  3 03:34 composer.json
-rw-r--r--  1 jfl www-data  1748 Jun  3 03:34 config.example.php
-rw-rw-r--  1 jfl www-data  1737 Jul 31 22:08 config.php
-rwxr-xr-x  1 jfl www-data  1475 Jun  3 03:34 CONTRIBUTING.md
drwxrwxr-x  2 jfl www-data  4096 Jun  3 03:34 data
-rwxr-xr-x  1 jfl www-data  1150 Jun  3 03:34 favicon.ico
-rw-r--r--  1 jfl www-data   158 Aug  3 15:40 index.html
-rwxr-xr-x  1 jfl www-data 19021 Jun  3 03:34 index.php
-rwxr-xr-x  1 jfl www-data   634 Jun  3 03:34 INSTALL.txt
drwxr-xr-x  2 jfl www-data  4096 Jun  3 03:34 js
drwxr-xr-x  2 jfl www-data  4096 Jun  3 03:34 languages
drwxr-xr-x  2 jfl www-data  4096 Jun  3 03:34 lib
-rwxr-xr-x  1 jfl www-data  1133 Jun  3 03:34 LICENSE.txt
drwxrwxr-x  2 jfl www-data  4096 Jun  3 03:34 plugins
-rwxr-xr-x  1 jfl www-data   672 Jun  3 03:34 README.md
-rwxr-xr-x  1 jfl www-data 24394 Jun  3 03:34 style_guide.php
drwxrwxr-x  3 jfl www-data  4096 Jun  3 03:34 themes
drwxrwxr-x  2 jfl www-data  4096 Jun  3 03:34 workspace
jfl@wsdeb:~$ 

nginx is running as www-data.www-data and I have added jfl to the www-data group.

**Comment by jfmxlgithub** [comment]
jfl@wsdeb:~$ ls -l /var/run/php5-fpm.sock 
srw-rw---- 1 www-data www-data 0 Aug  2 08:14 /var/run/php5-fpm.sock
jfl@wsdeb:~$ ps ax | grep php
15554 ?        Ss     0:06 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)                    
15556 ?        S      0:00 php-fpm: pool www                                                       
15557 ?        S      0:00 php-fpm: pool www                                                       
30661 pts/2    S+     0:00 grep php

root@wsdeb:/home/jfl# ls /etc/php5/fpm/conf.d/
05-opcache.ini	10-pdo.ini  20-json.ini  20-readline.ini

jfl@wsdeb:~$ 
jfl@wsdeb:~$ cat  /etc/php5/fpm/php-fpm.conf 
;;;;;;;;;;;;;;;;;;;;;
; FPM Configuration ;
;;;;;;;;;;;;;;;;;;;;;

; All relative paths in this configuration file are relative to PHP's install
; prefix (/usr). This prefix can be dynamically changed by using the
; '-p' argument from the command line.

; Include one or more files. If glob(3) exists, it is used to include a bunch of
; files from a glob(3) pattern. This directive can be used everywhere in the
; file.
; Relative path can also be used. They will be prefixed by:
;  - the global prefix if it's been set (-p argument)
;  - /usr otherwise
;include=/etc/php5/fpm/*.conf

;;;;;;;;;;;;;;;;;;
; Global Options ;
;;;;;;;;;;;;;;;;;;

[global]
; Pid file
; Note: the default prefix is /var
; Default Value: none
pid = /run/php5-fpm.pid

; Error log file
; If it's set to "syslog", log is sent to syslogd instead of being written
; in a local file.
; Note: the default prefix is /var
; Default Value: log/php-fpm.log
error_log = /var/log/php5-fpm.log

; syslog_facility is used to specify what type of program is logging the
; message. This lets syslogd specify that messages from different facilities
; will be handled differently.
; See syslog(3) for possible values (ex daemon equiv LOG_DAEMON)
; Default Value: daemon
;syslog.facility = daemon

; syslog_ident is prepended to every message. If you have multiple FPM
; instances running on the same server, you can change the default value
; which must suit common needs.
; Default Value: php-fpm
;syslog.ident = php-fpm

; Log level
; Possible Values: alert, error, warning, notice, debug
; Default Value: notice
;log_level = notice

; If this number of child processes exit with SIGSEGV or SIGBUS within the time
; interval set by emergency_restart_interval then FPM will restart. A value
; of '0' means 'Off'.
; Default Value: 0
;emergency_restart_threshold = 0

; Interval of time used by emergency_restart_interval to determine when 
; a graceful restart will be initiated.  This can be useful to work around
; accidental corruptions in an accelerator's shared memory.
; Available Units: s(econds), m(inutes), h(ours), or d(ays)
; Default Unit: seconds
; Default Value: 0
;emergency_restart_interval = 0

; Time limit for child processes to wait for a reaction on signals from master.
; Available units: s(econds), m(inutes), h(ours), or d(ays)
; Default Unit: seconds
; Default Value: 0
;process_control_timeout = 0

; The maximum number of processes FPM will fork. This has been design to control
; the global number of processes when using dynamic PM within a lot of pools.
; Use it with caution.
; Note: A value of 0 indicates no limit
; Default Value: 0
; process.max = 128

; Specify the nice(2) priority to apply to the master process (only if set)
; The value can vary from -19 (highest priority) to 20 (lower priority)
; Note: - It will only work if the FPM master process is launched as root
;       - The pool process will inherit the master process priority
;         unless it specified otherwise
; Default Value: no set
; process.priority = -19

; Send FPM to background. Set to 'no' to keep FPM in foreground for debugging.
; Default Value: yes
;daemonize = yes
 
; Set open file descriptor rlimit for the master process.
; Default Value: system defined value
;rlimit_files = 1024
 
; Set max core size rlimit for the master process.
; Possible Values: 'unlimited' or an integer greater or equal to 0
; Default Value: system defined value
;rlimit_core = 0

; Specify the event mechanism FPM will use. The following is available:
; - select     (any POSIX os)
; - poll       (any POSIX os)
; - epoll      (linux >= 2.5.44)
; - kqueue     (FreeBSD >= 4.1, OpenBSD >= 2.9, NetBSD >= 2.0)
; - /dev/poll  (Solaris >= 7)
; - port       (Solaris >= 10)
; Default Value: not set (auto detection)
;events.mechanism = epoll

; When FPM is build with systemd integration, specify the interval,
; in second, between health report notification to systemd.
; Set to 0 to disable.
; Available Units: s(econds), m(inutes), h(ours)
; Default Unit: seconds
; Default value: 10
;systemd_interval = 10

;;;;;;;;;;;;;;;;;;;;
; Pool Definitions ; 
;;;;;;;;;;;;;;;;;;;;

; Multiple pools of child processes may be started with different listening
; ports and different management options.  The name of the pool will be
; used in logs and stats. There is no limitation on the number of pools which
; FPM can handle. Your system will tell you anyway :)

; To configure the pools it is recommended to have one .conf file per
; pool in the following directory:
include=/etc/php5/fpm/pool.d/*.conf

jfl@wsdeb:~$

**Comment by dugite-code** [comment]
add the line: `fastcgi_param SCRIPT_FILENAME $request_filename;` to the php section. It got it working on my install

**Comment by jfmxlgithub** [comment]
bingo! looks like. Is that option discussed in the documantation somewhere?

Thank you Professor Doctor dugite-code, Sir!

**Comment by dugite-code** [comment]
No it's not in the documentation. From my understanding it's not always necessary to define the script filename explicitly so that might be why it's not included.

No worries Glad I could help

**Comment by jfmxlgithub** [comment]
I cannot change the theme ...

-rwxrwxrwx 1 jfl www-data 1638 Aug  4 08:32 config.php
drwxrwxrwx 2 jfl www-data 4096 Aug  4 08:33 data/
drwxrwxrwx 2 jfl www-data 4096 Jun  3 03:34 plugins/
drwxrwxrwx 3 jfl www-data 4096 Jun  3 03:34 themes/
drwxrwxrwx 3 jfl www-data 4096 Aug  4 08:32 workspace/

... I had the directories at 775 and the config.php at 664, I'd think that would be sufficient ... If permissions are my problem.

**Comment by dugite-code** [comment]
Are you changing the editor theme? That will only show when you have a file open. The system them requires you to replace the default folder.

See: https://github.com/Codiad/Codiad/wiki/Theme for details

**Comment by jfmxlgithub** [comment]
Well ... at least I have black characters on a white backgound in the file window. The rest is still all black ... I must be getting old (I am!) ... that depresses the heck (bowdlerized) out of me. I'll mess around and figure it out. Thanks again for all your help.
