### ISSUE TITLE
Upload site to FTP

### ISSUE THREAD

**Issue by roamn** [Codiad/Codiad#857]
Hi.
I create little plugin, that upload site to ftp, use settings from _ftp.json file in root of project, like SFTP for Sublime.
It is in the testing phase .
Not yet implemented the function of saving the settings from dialog box.
May be already exist such plugin? I couldnt find.
http://i.imgur.com/DLa9aXl.png
http://i.imgur.com/vGW35Qw.png

**Comment by daeks** [comment]
There is already a FTP plugin available at http://market.codiad.com/ (CodeTransfer), but you are welcome to distribute your plugin as well.
