### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by Ayantir** [Codiad/Codiad#858]
Could you add an option/plugin to set the default language of a project, so users don't have to set it at 1st login ?

Can be added to system options panel per exemple if we change it after.

**Comment by Ayantir** [comment]
I found it myself by adding in config.php

define("LANGUAGE", "fr");

Could you please add in comments in the file and/or in the wiki all things we could define without searching in source code ? or add it in the installer :)

**Comment by daeks** [comment]
It is already in the example configuration:

https://github.com/Codiad/Codiad/blob/master/config.example.php#L31

**Comment by Wessix** [comment]
Setting default language to "de" seems not to work in my installation, while changing it manually to Deutsch/German at "more" on login works. Setting it to "fr" for example works directly

**Comment by Filippo95** [comment]
when i try to install for the first time, default language was en, now when it's installed it's in russian, how can i change in en?
