### ISSUE TITLE
Archives plugin 500 error

### ISSUE THREAD

**Issue by Chris-ISN** [Codiad/Codiad#861]
I installed the Archives plugin from the marketplace and it appears to be installed properly, but when we right-click on an archive and choose "Extract" nothing happens (the loading modal opens but never goes away) and the following error 500 is logged in the site's error_log file:

```
mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '[' in /home/dev/public_html/apps/codiad/plugins/Codiad-Archives-master/functions.php on line 34, referer: http://somedomain.com/apps/codiad/
```

We are running PHP 5.3.3 on CentOS 6.4.

Does anyone know how to fix this?

**Comment by snikolow** [comment]
As of version 5.4.0, PHP introduced the short syntax for arrays - `$myArray = [];`. The file your error points to, have a definition for an array like that. And since your php version is 5.3.3, you are getting this error.

**Comment by Chris-ISN** [comment]
Great response, thanks @snikolow. Just installed PHP 5.4 from the CentOS SCL repository and the plugin works great.

**Comment by daeks** [comment]
just as note: please contact the plugin owner directly for issues in plugins
