### ISSUE TITLE
Editor behaving strange

### ISSUE THREAD

**Issue by chrisiaut** [Codiad/Codiad#863]
Since a few weeks I have noticed a weird problem on just one of my codiad instances.

When I want to add code and I press a key, the key gets printed multiple times and I can't delete the text. Coding is impossible.

Also the name of the opened file is not showing in the tab (the tabs are missing).

I have not added any addons before this happened.

You can see the problems [in this gif](https://imgrush.com/bonyVoSTpsyZ) (actually mp4)

**Comment by dugite-code** [comment]
I notice you have several plugins installed. Remove them and re-add one by one. I had a similar issue with the markdown links plugin

**Comment by chrisiaut** [comment]
That resolved my problem, Thanks!
