### ISSUE TITLE
lost login/passwd

### ISSUE THREAD

**Issue by jfmxlgithub** [Codiad/Codiad#864]
I have forgotten my codiad login and or passwd. How do i recover?

**Comment by jfmxlgithub** [comment]
Is this project attentive to the public? or is it principles only?

**Comment by dugite-code** [comment]
It's stored in `./data/users.php` if you have access to the server you can recover it there. A password recovery option is probably on the to-do list.

**Comment by jfmxlgithub** [comment]
Thanks again dugite-code. I don't really mean to be snarky, but it looks as though there's not much action here. Thanks to the developers for sharing their code ... but maybe you need to be a developer to use the project? Not too much in the way of documentation, although I can certainly understand if it is the case that codiad was built to serve the needs of those who built it, who don't need help in using it, who nonetheless generously share the code with us all but who don't have the time to fool with people who just ride on their coattails, like myself. I guess I'll have to try to read the code.

Thanks again.

**Comment by jfmxlgithub** [comment]
Thanks. I rarely check this email. I'll try to have a look at the code. I found my account ... but the password is hashed, I'll have to discover what hash is used first.

I've nearly go the Thai translation of the menu 'done'. I'll post it at the store when I do have. Codiad does not handle Thai text correctly. It's ok with one character after another, but Thai has over and under verbs and tone marks and Codiad - and most other editors - make a mess of it. So I don't know that Codiad is of any value to Thais ... they'd need two editors. And the second one would probably be sufficient so they wouldn't need Codiad. I imagine the editor is javascript? maybe there's a javascript editor that can handle Thai ... and lots of other languages that are more than just abc.

As I say I'll try to look at the code.

Thanks for all your help.
--
"This message may have been intercepted and read by U.S. government agencies including the FBI, CIA, and NSA without notice or warrant or knowledge of sender or recipient."

John Francis Lee
246/3 Thanon Kaew Wai
T.Ropwiang A.Mueang J.Chiangrai 57000
Thailand

--------------------------------------------
On Wed, 9/23/15, dugite-code <notifications@github.com> wrote:

 Subject: Re: [Codiad] lost login/passwd (#864)
 To: "Codiad/Codiad" <Codiad@noreply.github.com>
 Cc: "jfmxlgithub" <jfmxl@yahoo.com>
 Date: Wednesday, September 23, 2015, 9:00 PM
 
 It's stored in
 ./data/users.php if you have access to the
 server you can recover it there. A password recovery option
 is probably on the to-do list.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Heath123** [comment]
It's MD5 then SHA1
