### ISSUE TITLE
How to modify syntax colouring?

### ISSUE THREAD

**Issue by Xosted** [Codiad/Codiad#866]
Hello,

First I want to thank you for the great work.
This is not an issue as such, but I couldn't find anywhere else to ask...
If I'm not satisfied with the syntax colouring for the language I use, how do I get to modify it?
Can you point to somewhere in the doc (maybe I missed that part) or name a file directly please?
Thanks

**Comment by daeks** [comment]
As we are based on ACE, you could have a look here: http://ace.c9.io/#nav=higlighter
