### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by dugite-code** [Codiad/Codiad#869]
When editing a text file (or a markdown file) is it possible to have the editor do spell checking? I see there is ext-spellcheck.js
 in the editor file but I can't figure out if it needs enabling.

I understand the browser's spell checking doesn't work with the ACE editor.

**Comment by dugite-code** [comment]
OK after some research it looks like the browser's spell checker is still working it's just the underlining that isn't working with the ACE editor.

**Comment by Andr3as** [comment]
:+1: 
following...
