### ISSUE TITLE
Can't find files?

### ISSUE THREAD

**Issue by dannysmc95** [Codiad/Codiad#881]
So I have just moved from a web server to a dedicated server and I installed codiad and all, now the sites directory and data is at /home/websites/ide but for some reason (when checking before installing), it says it can't find anything? Everything is writable? So is there something I am missing?

Thanks, good work though!

**Comment by abelbacchus** [comment]
Had a similar problem. Tried reinstalling but everything is messed up now. I'll let you know if I resolved it.

**Comment by daeks** [comment]
you have to check data/projects.php for the right paths, depending wether you are using absolute paths or not
