### ISSUE TITLE
Incorrect scroll behavior on iOS

### ISSUE THREAD

**Issue by sthainzl** [Codiad/Codiad#882]
Hello,

Both in Safari and Chrome the middle pane is not scrolling. This is on iOS 9.1.
Tested with local installation and files as well as the public demo.
Also tested with iPhone and iPad.

Thanks!

**Comment by sthainzl** [comment]
Amendment:
Same behaviour in Safari on iOS 6.1.3.
Correct behaviour in Safari on Mac OS X 10.11.

Local installation mentioned above is 2.6.6.

Thanks!

**Comment by daeks** [comment]
ios is currently not supported

**Comment by tejastank** [comment]
Expected iOS Support highly ...
