### ISSUE TITLE
Cannot read property 'setTheme' of undefined

### ISSUE THREAD

**Issue by dannysmc95** [Codiad/Codiad#884]
For some reason when loading a file into the ace editor it errors with the following:

```Uncaught TypeError: Cannot read property 'setTheme' of undefined codiad.editor.applySettings @ init.js:455codiad.editor.setSession @ init.js:804fn @ init.js:87o @ jquery.min.js:2p.fireWith @ jquery.min.js:2w @ jquery.min.js:4d @ jquery.min.js:4XMLHttpRequest.send (async)send @ jquery.min.js:4f.extend.ajax @ jquery.min.js:4$.loadScript @ system.js:36 codiad.active.open @ init.js:95(anonymous function) @ init.js:378o @ jquery.min.js:2p.fireWith @ jquery.min.js:2w @ jquery.min.js:4d @ jquery.min.js:4XMLHttpRequest.send (async)send @ jquery.min.js:4f.extend.ajax @ jquery.min.js:4f.(anonymous function) @ jquery.min.js:4codiad.filemanager.openFile @ init.js:374(anonymous function) @ init.js:72f.event.dispatch @ jquery.min.js:3h.handle.i @ jquery.min.js:3```

**Comment by daeks** [comment]
update codiad and/or refresh your browser's cache In case of any further issue please post some more details about your server and local environment
