### ISSUE TITLE
Is it possible to upload php files?

### ISSUE THREAD

**Issue by sat2ep** [Codiad/Codiad#886]
First of all, this is a fantastic job!
My question is, if it's possible to upload files with php extension using the included uploader.
Thank you in advance.

**Comment by daeks** [comment]
I dont know there any limitation

**Comment by sat2ep** [comment]
Not whether this will be my setup, but when I try to upload multiple files, with extension php it never do, and not even giving any error

**Comment by jamieisboss** [comment]
It definitely works for me, have you tried uploading a file as a .txt then changing the extension? 

If your webhost or isp is messing with what you can do, you could create an ssl certificate and install it for your codiad instance, that would probably stop them, unless it's the host and they've somehow set things up so you can't have php files,.

**Comment by daeks** [comment]
Maybe it is restricted
