### ISSUE TITLE
Can't get to open file

### ISSUE THREAD

**Issue by delacroix99** [Codiad/Codiad#895]
Hello,
I am having trouble opening files that contains
```
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<body>
text text text
</body>
</html>
```

For a couple of month it worked and now it just stopped. Server is Ubuntu 14.04, nginx (1.9.7) with PHP 5.5.30.

Did anyone faced similar issue?

Thank you

This is what happens in Codiad. Error log does not show anything.
![2016-02-26](https://cloud.githubusercontent.com/assets/17490303/13345526/ba56e3ec-dc5f-11e5-8292-1b59dba1a350.png)

**Comment by daeks** [comment]
to figure out the problem, do the following:

Open the developer console with 12, switch to the network tab and after clearing existing output, press index.phtml again. Check the output of the controller if it is a valid json object and/or post the result here.

components/filemanager/controller.php?action=open&path=<yourpath>

**Comment by delacroix99** [comment]
Hello Daeks,

This is what I can see. Strange that the controller.php gives back the data on every other file, except the one that has < html > < head > etc.

![codiad_1](https://cloud.githubusercontent.com/assets/17490303/13354654/be8de680-dc9c-11e5-8887-bf4cfd90759d.png)
![codiad_2](https://cloud.githubusercontent.com/assets/17490303/13354655/beb7aa74-dc9c-11e5-9deb-aa1cf3bd8c67.png)

**Comment by daeks** [comment]
the output iof the controller.php looks a bit wired. is that all the output? At least I am missing the losing brackets

**Comment by delacroix99** [comment]
Yes, but then I clicked VM258:1 error that I got from the Chrome Console. Found out, that it is the New Relic app that gives this.

Part of the code it gave:
`{"status":"success","data":{"content":"<!DOCTYPE html>\n<html class=\"no-js\" lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" \/><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var o=e[n]={exports:{}};t[n][0].call(o.exports,function(e){var o=t[n][1][e];return r(o||e)},o,o.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<n.length;o++)r(n[o]);return r}({QJf3ax:[function(t,e){function n(){}function r(t){function e(t){return t&&t instanceof n?t:t?a(t,i,o):o()}function c(n,r,o){t&&t(n,r,o);for(var i=e(o),a=f(n),c=a.length,u=0;c>u;u++)a[u].apply(i,r);return i}function u(t,e){p[t]=f(t).concat(e)}function f(t){return p[t]||[]}function s(){return r(c)}var p={};return{on:u,emit:c,create:s,listeners:f,context:e,_events:p}}function o(){return new n}var i="nr@context",a=t("gos");e.exports=r()},{gos:"7eSDFh"}],ee:[function(t,e){e.exports=t("QJf3ax")},{}],3:[function(t,e){function n(t){return function(){r(t,[(new Date).getTime()].concat(i(arguments)))}}var r=t("handle"),o=t(1),i=t(2);"undefined"==typeof window.newrelic&&(newrelic=window.NREUM);`

Stopped new relic and now it loads the content. Thanks a lot for helping me debugging this issue.

**Comment by daeks** [comment]
for ref. https://github.com/Codiad/Codiad/issues/700 and
