### ISSUE TITLE
Add Arduino INO syntax highlighting

### ISSUE THREAD

**Issue by cdeschenes** [Codiad/Codiad#900]
Would be it possible to add syntex highlighting for INO files? There is a project to add it to VIM and was wondering if that information may help aid the process of implementing it on Codiad.

https://github.com/sudar/vim-arduino-syntax/blob/master/syntax/arduino.vim

Thanks
-Cody

**Comment by daeks** [comment]
As Codiad is based of ace (https://github.com/ajaxorg/ace) this request has to be forwarded to them

**Comment by cdeschenes** [comment]
Awesome. thanks for the help. I am really enjoying Codiad.

**Comment by daeks** [comment]
Looking at https://github.com/ajaxorg/ace/blob/3e38c41a6663f523282130a5ddde3f2d07119e2b/lib/ace/ext/modelist.js#L55 it seems to be that INO is handled with C_cpp mode

**Comment by cdeschenes** [comment]
Thanks for the info.
