### ISSUE TITLE
Andr3as can help me? :D Please

### ISSUE THREAD

**Issue by clubinformatico** [Codiad/Codiad#913]
I have installed now your plugin of autocomplete!
But when i keyup display strange keys...
Look i capture a video when im writing "if(isset" 
[https://www.youtube.com/watch?v=-CHxJ3PAVds&feature=youtu.be](url)

**Comment by Andr3as** [comment]
Yes, that's a bug. I fixed it with the [latest](https://github.com/Andr3as/Codiad-CompletePlus/commit/3135b33f4074525046114a9129ff0ee247a3124a) version of the plugin today.

Please create next time an issue in the repository for [CompletePlus](https://github.com/Andr3as/Codiad-CompletePlus) and choose a proper title.
