### ISSUE TITLE
Unable to fully install on PHP7

### ISSUE THREAD

**Issue by lilltiger** [Codiad/Codiad#914]
The issue is that the config.php gets emptied and the user.php etc in the data folder also is completely empty.

But I do not know why it does that, still makes me unable to install Codiad on my php7 server.

This seems to be the same issue as #831

**Comment by azlux** [comment]
It's working on mine.
Check your dependencies, because php7 don't have the same php7.0-commun package than php5.
It missing php7.0-zip, php7.0-xml and php7.0-mbstring.
Check this possibility .

**Comment by lilltiger** [comment]
# php -m

[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
gettext
hash
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
SimpleXML
SPL
ssh2
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

---------

They are all built-in, any other idea?

**Comment by lilltiger** [comment]
I found the issue, I had ran out of free diskspace but the fopen.. write.. functions does not war about that at all.

I would recommend you to change:
`    function saveFile($file,$data){
        $write = fopen($file, 'wb') or die("can't open file");
        fwrite($write, $data);
        fclose($write);
    }
`
to:

`    function saveFile($file,$data){
        file_put_contents( $file, $data );
    }
`

As this produces better error reporting.

**Comment by daeks** [comment]
file_put_contents is the worst method you can use, esp for large files.

**Comment by azlux** [comment]
@lilltiger For your case, I think it's better to check your available space with the [disk-free-space](http://php.net/manual/en/function.disk-free-space.php) function before writing. (just take care of your open_basedir variables)

**Comment by lilltiger** [comment]
@daeks well these files are small, and file_put_content did give appropriate error messages, while fopen does not.

@azlux: That can also be an option, but what other errors does the fopen way fail to report on. There should be a proper way to write too files.
