### ISSUE TITLE
Only 9 lines visible in Chrome (strange bug?)

### ISSUE THREAD

**Issue by 2rcsanyi** [Codiad/Codiad#919]
Hi! After opening the website, sometimes only 9 lines is visible and if I try to scroll down, the bug remains.
It's only in Chrome (couldn't reproduce this bug in FF) and doesn't happen always, but often enough to be really annoying :(
Is it a bug in Codiad or in Ace Editor? I couldn't find anything about it.

This is the expected result:
![image](https://cloud.githubusercontent.com/assets/15998297/15899587/8376516c-2d9c-11e6-881f-8755143463d8.png)

And that's what I get:
![image](https://cloud.githubusercontent.com/assets/15998297/15899551/61eddf1a-2d9c-11e6-8df7-985dbb292940.png)
After scrolling:
![image](https://cloud.githubusercontent.com/assets/15998297/15899558/6a03cd86-2d9c-11e6-9e16-4b058d1ebba8.png)

Resizing the window or reopening the file is a temporary fix - but after I reopen the URL, there is a chance again to not seeing more than 9 lines.

Please help me solve this problem! Thank you!

**Comment by franga2000** [comment]
I get this bug in Firefox too. It shows the first 8 lines and it happens on almost every refresh. If I have multiple tabs open, none of them appear active (lighter gray) and sometimes the text is from another tab entirely.
