### ISSUE TITLE
Suggest a Docker install

### ISSUE THREAD

**Issue by wernight** [Codiad/Codiad#925]
If I may suggest that you add to your Wi-Ki a Docker "install". You're welcome to refer to the image I recently created https://hub.docker.com/r/wernight/codiad/, or use another.

**Comment by daeks** [comment]
the wiki can be edited by everyone. Feel free to add it by yourself.

**Comment by wernight** [comment]
Ok, I didn't want to self-promote without approval so feel free also to update.
