### ISSUE TITLE
test with travis-ci but never success

### ISSUE THREAD

**Issue by NewFuture** [Codiad/Codiad#948]
I find all the tests failed on [travis-ci](https://travis-ci.org/Codiad/Codiad/branches).

so , Why do we do this?

**Comment by daeks** [comment]
the intention was to have a proper formatting applied to the whole source code. Currently nobody had the time to align the format with the syntax checked by travis.

**Comment by NewFuture** [comment]
:joy_cat:  oh,  a sad story :crying_cat_face: 

For this problems, there are two ways :

* once for all 
formatting the codes by travis  and then commit and push the changes back 

*  semi-automatic
  1. use some tools or config for editor or  to auto format on save  llike `editorconfig` and `phpcs`
  2. or use git hook to check syntax or auto foramt on commit
  3. refuse the push or pr when build fails travis [manually manage]

but we shouldn't make it still failing.  
So, which one is better , and should we change it :question:  

In addition, it's better run some  necessary tests on travis. :smile_cat:

**Comment by daeks** [comment]
Personally I would like to have to code formatted as this was the original intention to do. Nevertheless this needs to be done on a seperate branch as there is no easy way to obtain any changes leading to bugs without deeper testing.

**Comment by NewFuture** [comment]
@daeks  i have modified most of the indents and space in components, and change the .tavis.yml to exclude some sniffer at current  make all passed  #950  :smile_cat: 

For further some class and method or const need to `rename`. but now, I `ignore` these to avoid leading to bugs. 
And , it's better to use the STRICT mode in future.

For more,  I add PHP7 in Travis, for future build and test.

In addition `*/*.dialog.php`  may need to be rewritten to pass the check , so  I skip those files.  
:cat:

**Comment by daeks** [comment]
👍
