### ISSUE TITLE
Update & Marketplace Server

### ISSUE THREAD

**Issue by Fluidbyte** [Codiad/Codiad#957]
I had previously been hosting the demo, update and marketplace server off a DigitalOcean host. Recently it was compromised and has been disconnected by DO in order to prevent malicious traffic. At this point I'm not able to take on the task of getting a new instance running, and furthermore - ensure it stays up reliably.

I'm looking to find someone who is willing to take this on. We were hosting it on a $5 box, so resources are low, but need someone who can handle maintenance, etc.

There are repos for the [market server](https://github.com/Codiad/Codiad-Market-Server), [update server](https://github.com/Codiad/Codiad-Update-Server) and [demo](https://github.com/Codiad/CodiadDemo)

I'm more than happy to point any DNS over as well.

**Comment by cheiff** [comment]
Hi @Fluidbyte ,

I would be more than happy to take over that task. 
What would you need me to do?

Thanks

**Comment by Fluidbyte** [comment]
We would need a server running with the market, update and demo (all of which have documentation). Once those are up and running somewhere I can point the DNS.

**Comment by cheiff** [comment]
OK. I'll try to set that up during the weekend. 

Thank you

**Comment by daeks** [comment]
@cheiff I can help with setup if it is required. the most important point is to get the automatic update running and the security stuff for the demo

@Fluidbyte is there a way to get the statistic dumps from the update / market?

**Comment by Fluidbyte** [comment]
I can see about getting a restore from the box. May be a couple days but I'll post here if I can pull anything.

**Comment by g0dless** [comment]
Hi averyone. For how long time does marketplace server need to be hosted ?
Is it a week or a month or a half year?

**Comment by cheiff** [comment]
Hi, 

I'll take over that, sorry I found no time over the weekend. 

I'll fix this asap.

**Comment by cheiff** [comment]
Hi,

demo is up and running at 149.202.62.249.
I'll set up market and update now.

**Comment by cheiff** [comment]
Hi again,
market and update server, both running at the same IP, 149.202.62.249.
Sorry for the delay. Please @Fluidbyte update the DNS when you can.
Thank you.
Best regards

**Comment by Fluidbyte** [comment]
I've updated the records for `update.codiad.com` and `market.codiad.com` so, once propagated, those should be fixed. Not sure if/how we want to handle the demo server.

**Comment by Fluidbyte** [comment]
Nevermind, demo's up on that server as well :)

**Comment by daeks** [comment]
@cheiff Calling the stats page it says ```Fatal error: Uncaught Error: Call to undefined function split()```. I guess you are running a PHP version newer/equal than 7.0.0?

**Comment by cheiff** [comment]
Yes,  it's PHP7. 
I'll change it to Php5.6 asap.
Didn't know.

**Comment by cheiff** [comment]
Changed to PHP5.6, all three sites. Let me know if you run into any other issues.
Thanks

**Comment by cheiff** [comment]
Oh, didn't see @daeks update about the explode().
Yes, automatic update is enabled on all three, but it won't run until 0:00h.
I will leave then 5.6 until tomorrow, then change it back to 7.

**Comment by cheiff** [comment]
@daeks Where is the stats page where you see the error?

**Comment by daeks** [comment]
@cheiff for ex. http://update.codiad.com/stats.php or http://market.codiad.com/stats.php

**Comment by cheiff** [comment]
OK, thanks.

**Comment by Fluidbyte** [comment]
it seems everything is up and running again, thanks @daeks and @cheiff for all your work on this!

**Comment by cheiff** [comment]
Thank you both!

**Comment by cheiff** [comment]
Updated to php7.0. Everything seems to work fine.
Thank you, best regards
