### ISSUE TITLE
Failsafe for deleting Codiad/workspace folder

### ISSUE THREAD

**Issue by jpl42** [Codiad/Codiad#964]
I was tidying up my server, and was planning on reinstalling Codiad once I decided a better place to put it. Before deleting it, I deleted the workspace folder. Doing this wiped almost everything (besides anything with root ownership) in my web root, I presume there is some sort of symlink here.

There should be some sort of failsafe in deleting the workspace folder, or some obvious warning somewhere like "DO NOT DELETE THE WORKSPACE FOLDER, IT WILL WIPE ANYTHING INSIDE YOUR PROJECT FOLDER". This project folder was the root `/var/www` of my web root. 

Stupidly I haven't backed up my server in over a week, so I watched everything I'm working on disappear. I couldn't even save the open files since Codiad stopped responding when I did this (the Codiad install was inside the web root folder).

I know there's no way I can save all my work, just please add some sort of warning somewhere so that people don't make the same mistake I did.

**Comment by daeks** [comment]
Deleting files is optional, so no further warning is required.

![image](https://cloud.githubusercontent.com/assets/3989440/20876677/fca178aa-bac3-11e6-965c-1c1bf07495b1.png)

**Comment by jpl42** [comment]
I was specifically talking about deleting the entire `workspace` folder inside the Codiad folder. My suggestion is for Codiad to detect the path on the server it is running from (maybe `/var/www/Codiad` for example), and present a warning if a user tries to delete this or any folder inside it.
