### ISSUE TITLE
Ubuntu Server 16.04.2

### ISSUE THREAD

**Issue by havretnet** [Codiad/Codiad#984]
On Ubuntu Server 16.04.2 and PHP7 you must install libapache2-mod-php, else it's doesn't works.

![image](https://cloud.githubusercontent.com/assets/26274033/23699748/97149e7e-03f0-11e7-84cb-0f01037e75a4.png)

**Comment by atomlab** [comment]
So, of course php don't work without apache2-mod-php if you use apache2. How else?

**Comment by havretnet** [comment]
I have never install "libapache2-mod-php" on my debian server (PHP5) and i've never had any problem.

**Comment by daeks** [comment]
The wiki can be edited by everyone. Please add it to the designated page.
