### ISSUE TITLE
White blank page on PHP 7.1

### ISSUE THREAD

**Issue by andrecavallari** [Codiad/Codiad#992]
I am trying to install Codiad in my vps but getting just a blank response...

**Comment by CheatCoder** [comment]
Can you give a little more information, it's working with PHP 7.1 on my server using Nginx.
Which Webserver you are using? Apache ... Nginx ... or a other one?

**Comment by andrecavallari** [comment]
I was using NGINX, dont know the problem but i reset my vps and now I got working
